# Generated by Django 6.0.4 on 2026-05-10 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beakon_core', '0048_entity_chart_template_vat_enabled'),
        ('organizations', '0003_backfill_selected_activities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Short label, e.g. 'Trip to Geneva — March 2026'.", max_length=200)),
                ('purpose', models.TextField(blank=True, help_text='Business purpose of the trip.')),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='CHF', help_text='Currency in which the claim totals are expressed.', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reimbursed', 'Reimbursed')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reimbursed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_trip_claims', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_claims', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(help_text='The entity that bears this cost.', on_delete=django.db.models.deletion.PROTECT, related_name='trip_claims', to='beakon_core.entity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_claims', to='organizations.organization')),
            ],
            options={
                'db_table': 'beakon_trip_claim',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('transport', 'Transport (flight, train, taxi)'), ('accommodation', 'Accommodation'), ('meals', 'Meals'), ('per_diem', 'Per diem'), ('entertainment', 'Entertainment'), ('fuel', 'Fuel'), ('mileage', 'Mileage'), ('conference', 'Conference / training'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('merchant', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount on the receipt, in `currency`.', max_digits=14)),
                ('currency', models.CharField(default='CHF', max_length=3)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=10, help_text='FX rate used to translate to the claim currency. Blank = same currency.', max_digits=20, null=True)),
                ('amount_in_claim_currency', models.DecimalField(decimal_places=2, help_text="Translated amount in the claim's currency.", max_digits=14)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, help_text='VAT included in `amount`, in the receipt currency. Optional.', max_digits=14, null=True)),
                ('receipt_url', models.URLField(blank=True, help_text='External link to the receipt image / PDF. v1 placeholder until Document module attaches files directly.', max_length=500)),
                ('billable_to_client', models.BooleanField(default=False, help_text='If true, this line can be invoiced to a client via the Disbursements flow.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='beakon_travel.tripclaim')),
            ],
            options={
                'db_table': 'beakon_trip_expense',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='tripclaim',
            index=models.Index(fields=['organization', 'status'], name='beakon_trip_organiz_b0e00f_idx'),
        ),
        migrations.AddIndex(
            model_name='tripclaim',
            index=models.Index(fields=['organization', 'created_by'], name='beakon_trip_organiz_40cc4c_idx'),
        ),
        migrations.AddIndex(
            model_name='tripexpense',
            index=models.Index(fields=['claim', 'category'], name='beakon_trip_claim_i_455e1f_idx'),
        ),
    ]
