# Generated by Django 6.0.4 on 2026-05-10 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_employment', '0001_initial'),
        ('beakon_travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripclaim',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Employee record for the claimant — auto-linked when the user has an Employee profile. Per the data-architecture principle: Travel references the canonical Employee row rather than duplicating identity fields.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_claims', to='beakon_employment.employee'),
        ),
    ]
