# Generated by Django 6.0.4 on 2026-05-10 18:16

import beakon_documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beakon_core', '0048_entity_chart_template_vat_enabled'),
        ('beakon_employment', '0001_initial'),
        ('organizations', '0003_backfill_selected_activities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Human-readable name. Defaults to the original filename if not supplied.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('contract', 'Contract'), ('statement', 'Statement'), ('policy', 'Policy'), ('certificate', 'Certificate'), ('tax', 'Tax document'), ('legal', 'Legal'), ('hr', 'HR / Employment'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(blank=True, help_text='Uploaded file. Either this or external_url must be set.', max_length=500, null=True, upload_to=beakon_documents.models._upload_path)),
                ('external_url', models.URLField(blank=True, help_text='Link to the document in an external store (cloud drive, DMS). Use when the file lives outside Beakon — for example a signed contract in DocuSign.', max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, help_text='SHA-256 hex digest of the file bytes. Blank for external_url-only documents.', max_length=64)),
                ('document_date', models.DateField(blank=True, help_text='Date on the document itself (signature date, statement as-of, certificate issue date). Distinct from upload date.', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beakon_deleted_general_documents', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='beakon_employment.employee')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='beakon_core.entity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beakon_uploaded_general_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'beakon_document',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['organization', 'category'], name='beakon_docu_organiz_cff9c8_idx'), models.Index(fields=['organization', 'is_deleted'], name='beakon_docu_organiz_ce8510_idx'), models.Index(fields=['entity'], name='beakon_docu_entity__8f1814_idx'), models.Index(fields=['employee'], name='beakon_docu_employe_cc1e4e_idx'), models.Index(fields=['content_hash'], name='beakon_docu_content_2cd06d_idx')],
            },
        ),
    ]
