# Generated by Django 6.0.4 on 2026-04-12 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('ai', 'AI')], default='user', max_length=20)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('post', 'Post'), ('reverse', 'Reverse'), ('approve', 'Approve'), ('reject', 'Reject'), ('login', 'Login'), ('logout', 'Logout'), ('close_period', 'Close Period'), ('reopen_period', 'Reopen Period'), ('reconcile', 'Reconcile'), ('import', 'Import'), ('export', 'Export')], max_length=50)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.BigIntegerField()),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='organizations.organization')),
            ],
            options={
                'db_table': 'audit_auditevent',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='audit_audit_organiz_4fc53a_idx'), models.Index(fields=['organization', 'object_type', 'object_id'], name='audit_audit_organiz_c73636_idx'), models.Index(fields=['actor'], name='audit_audit_actor_i_40b234_idx')],
            },
        ),
    ]
