# Generated by Django 6.0.4 on 2026-05-10 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beakon_core', '0048_entity_chart_template_vat_enabled'),
        ('organizations', '0003_backfill_selected_activities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(help_text='Unique short identifier within the organization. Auto-generated from name when not supplied.', max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(blank=True, help_text="Job title — e.g. 'Senior Accountant', 'CFO', 'Trainee'.", max_length=150)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contractor', 'Contractor'), ('intern', 'Intern'), ('other', 'Other')], default='full_time', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, help_text='Date employment ended. Leave blank for active employees.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(help_text='The entity that employs this person.', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='beakon_core.entity')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='beakon_employment.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.organization')),
                ('user', models.OneToOneField(blank=True, help_text='Beakon login linked to this employee. Optional — not every employee has an account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'beakon_employee',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='beakon_empl_organiz_215ac6_idx'), models.Index(fields=['organization', 'entity'], name='beakon_empl_organiz_917184_idx')],
                'unique_together': {('organization', 'employee_number')},
            },
        ),
    ]
