"""Introspect the live Django schema and emit a markdown report of
every model + FK relationship grouped by domain.

Output: docs/database-relationships.md

Run: python scripts/_generate_db_relationship_report.py
"""
import os
import sys
import django
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "digits_clone.settings")
django.setup()

from django.apps import apps


# Domain grouping — purely for the report's readability.
DOMAINS = {
    "Core ledger": [
        "Entity", "Currency", "FXRate", "AccountGroup",
        "CoADefinition", "Account", "CoAMapping",
        "DimensionType", "DimensionValue", "DimensionValidationRule",
        "ControlledListEntry", "Period", "CustomAccountSubtype", "CustomEntityType",
    ],
    "Journal engine": [
        "JournalEntry", "JournalLine", "IntercompanyGroup", "ApprovalAction",
    ],
    "AP / AR": [
        "Vendor", "Customer", "Party",
        "Bill", "BillLine",
        "Invoice", "InvoiceLine",
    ],
    "Documents": [
        "SourceDocument",
    ],
    "Tax / VAT": [
        "TaxCode",
    ],
    "Recognition (multi-period)": [
        "RecognitionRule", "RecognitionSchedule",
    ],
    "Workbook masters": [
        "Loan", "Instrument", "Portfolio", "Custodian",
        "RelatedParty", "Counterparty", "BankAccount",
        "Property", "Policy", "TaxLot",
    ],
    "Architecture extensions": [
        "Pension", "Commitment",
    ],
    "Workflow / docs": [
        "WorkflowDiagram",
    ],
    "Banking feeder": [
        "BankTransaction", "FeedImport",
    ],
}

# Ignore models in these apps for the report.
SKIP_APPS = {"admin", "auth", "contenttypes", "sessions", "messages",
             "token_blacklist", "audit"}


def collect_models():
    by_name = {}
    for cfg in apps.get_app_configs():
        if cfg.label in SKIP_APPS:
            continue
        for model in cfg.get_models():
            by_name[model.__name__] = model
    return by_name


def _on_delete_label(fn):
    """Return a friendly label for the FK on_delete handler."""
    if fn is None:
        return "?"
    name = getattr(fn, "__name__", None) or repr(fn)
    # Django stores on_delete as a function reference — its module path tells us
    # which behaviour it is: CASCADE, SET_NULL, PROTECT, SET_DEFAULT, DO_NOTHING.
    return name.upper()


def fk_rows(model):
    """Yield dicts for each FK / OneToOne field on `model`."""
    for f in model._meta.get_fields():
        if not (f.many_to_one or f.one_to_one):
            continue
        if getattr(f, "auto_created", False):
            continue
        target = f.related_model
        on_delete_attr = getattr(getattr(f, "remote_field", None), "on_delete", None) \
                        or getattr(f, "on_delete", None)
        on_delete_name = _on_delete_label(on_delete_attr)
        yield {
            "field": f.name,
            "to_app": target._meta.app_label if target else "?",
            "to_model": target.__name__ if target else "?",
            "to_table": target._meta.db_table if target else "?",
            "on_delete": on_delete_name,
            "nullable": bool(getattr(f, "null", False)),
            "help": (getattr(f, "help_text", "") or "").strip(),
        }


def reverse_rels(by_name, target_name):
    """Find every FK across the project that points to `target_name`."""
    out = []
    for src_name, src_model in by_name.items():
        for row in fk_rows(src_model):
            if row["to_model"] == target_name:
                out.append({
                    "from_table": src_model._meta.db_table,
                    "from_model": src_name,
                    "field": row["field"],
                    "on_delete": row["on_delete"],
                    "nullable": row["nullable"],
                })
    return out


def main():
    by_name = collect_models()

    out = ["# Beakon — Database Relationships",
           "",
           "Auto-generated by `scripts/_generate_db_relationship_report.py`. "
           "This is a faithful snapshot of every Django model and its foreign-key "
           "links across the project, grouped by domain.",
           "",
           f"Total models in scope: **{len(by_name)}**",
           ""]

    # ── Per-domain detail ────────────────────────────────────────────
    seen = set()
    for domain, names in DOMAINS.items():
        models_here = [(n, by_name[n]) for n in names if n in by_name]
        if not models_here:
            continue
        out.append(f"## {domain}")
        out.append("")
        for name, model in models_here:
            seen.add(name)
            out.append(f"### `{name}` &mdash; `{model._meta.db_table}`")
            doc = (model.__doc__ or "").strip().split("\n\n")[0].replace("\n", " ").strip()
            if doc:
                out.append(f"> {doc[:280]}{'…' if len(doc) > 280 else ''}")
                out.append("")
            fks = list(fk_rows(model))
            if fks:
                out.append("| Field | → Target | On delete | Nullable |")
                out.append("|---|---|---|---|")
                for f in fks:
                    target = f"`{f['to_app']}.{f['to_model']}`"
                    out.append(
                        f"| `{f['field']}` | {target} | {f['on_delete']} | "
                        f"{'yes' if f['nullable'] else 'no'} |"
                    )
            else:
                out.append("_No outgoing foreign keys (root entity in its slice)._")
            out.append("")
        out.append("")

    # ── Anything we forgot ───────────────────────────────────────────
    leftover = [n for n in by_name if n not in seen]
    if leftover:
        out.append("## Other models")
        out.append("")
        for name in sorted(leftover):
            model = by_name[name]
            out.append(f"### `{name}` &mdash; `{model._meta.db_table}`")
            fks = list(fk_rows(model))
            if fks:
                out.append("")
                out.append("| Field | → Target | On delete | Nullable |")
                out.append("|---|---|---|---|")
                for f in fks:
                    target = f"`{f['to_app']}.{f['to_model']}`"
                    out.append(
                        f"| `{f['field']}` | {target} | {f['on_delete']} | "
                        f"{'yes' if f['nullable'] else 'no'} |"
                    )
            out.append("")

    # ── Reverse-relationship summary for the high-traffic targets ─────
    out.append("## Reverse-relationship hot spots")
    out.append("")
    out.append("These models are FK targets from many places — touching them "
               "ripples across the system. Useful when planning schema changes.")
    out.append("")
    hot = ["Organization", "User", "Entity", "Account", "JournalEntry",
           "RelatedParty", "Counterparty", "Portfolio", "Custodian"]
    for target in hot:
        rev = reverse_rels(by_name, target)
        if not rev:
            continue
        out.append(f"### `{target}` is referenced by {len(rev)} place(s)")
        out.append("")
        out.append("| From model | Field | On delete | Nullable |")
        out.append("|---|---|---|---|")
        for r in rev:
            out.append(
                f"| `{r['from_model']}` | `{r['field']}` | "
                f"{r['on_delete']} | {'yes' if r['nullable'] else 'no'} |"
            )
        out.append("")

    # ── Footer ──
    from datetime import datetime
    out.append("---")
    out.append(f"Generated {datetime.now().strftime('%Y-%m-%d %H:%M')} from a "
               "live Django introspection. Re-run the script after schema changes "
               "to refresh.")

    md_text = "\n".join(out)
    target_path = Path(__file__).resolve().parent.parent / "docs" / "database-relationships.md"
    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(md_text, encoding="utf-8")
    print(f"Wrote {target_path} ({target_path.stat().st_size} bytes)")

    # Also emit a print-friendly HTML version. Self-contained — no external CSS.
    html_path = target_path.with_suffix(".html")
    html_path.write_text(_render_html(md_text), encoding="utf-8")
    print(f"Wrote {html_path} ({html_path.stat().st_size} bytes)")


# ── Tiny markdown → HTML converter (handles the subset used in this report) ──

def _esc(s: str) -> str:
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def _render_inline(s: str) -> str:
    """Inline transforms — keeps existing HTML entities intact."""
    import re
    # `code` spans
    s = re.sub(r"`([^`]+)`", lambda m: f"<code>{_esc(m.group(1))}</code>", s)
    # **bold**
    s = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", s)
    # _italic_  (only when surrounded by spaces or punctuation to avoid file_paths)
    s = re.sub(r"(^|[\s(])_([^_]+)_(?=[\s.,)]|$)",
               r"\1<em>\2</em>", s)
    return s


def _render_html(md: str) -> str:
    """Convert our specific markdown subset to a self-contained printable HTML."""
    lines = md.split("\n")
    body: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Horizontal rule
        if stripped == "---":
            body.append("<hr>")
            i += 1; continue

        # Headings
        if stripped.startswith("### "):
            body.append(f"<h3>{_render_inline(stripped[4:])}</h3>"); i += 1; continue
        if stripped.startswith("## "):
            body.append(f"<h2>{_render_inline(stripped[3:])}</h2>"); i += 1; continue
        if stripped.startswith("# "):
            body.append(f"<h1>{_render_inline(stripped[2:])}</h1>"); i += 1; continue

        # Blockquote
        if stripped.startswith("> "):
            body.append(f"<blockquote>{_render_inline(stripped[2:])}</blockquote>")
            i += 1; continue

        # Tables: a row starting with `|` followed by a separator row `|---|`.
        if stripped.startswith("|") and i + 1 < len(lines) \
                and set(lines[i + 1].strip().replace("|", "").replace("-", "").replace(":", "").strip()) <= set():
            # Header row
            headers = [c.strip() for c in stripped.strip("|").split("|")]
            body.append("<table>")
            body.append("  <thead><tr>" + "".join(
                f"<th>{_render_inline(h)}</th>" for h in headers
            ) + "</tr></thead>")
            body.append("  <tbody>")
            i += 2  # skip separator
            while i < len(lines) and lines[i].strip().startswith("|"):
                cells = [c.strip() for c in lines[i].strip().strip("|").split("|")]
                body.append("    <tr>" + "".join(
                    f"<td>{_render_inline(c)}</td>" for c in cells
                ) + "</tr>")
                i += 1
            body.append("  </tbody></table>")
            continue

        # Empty line
        if not stripped:
            i += 1; continue

        # Plain paragraph
        body.append(f"<p>{_render_inline(stripped)}</p>")
        i += 1

    inner = "\n".join(body)
    css = """
        :root { color-scheme: light; }
        * { box-sizing: border-box; }
        body { font: 13px/1.55 system-ui, -apple-system, "Segoe UI", sans-serif;
               color: #1f2937; background: #fff; max-width: 1100px;
               margin: 28px auto; padding: 0 24px; }
        h1 { font-size: 26px; margin: 0 0 8px; letter-spacing: -0.01em; }
        h2 { font-size: 18px; margin: 32px 0 12px;
             padding-bottom: 6px; border-bottom: 1px solid #e5e7eb;
             color: #0f172a; }
        h3 { font-size: 14px; margin: 22px 0 6px; color: #0f172a;
             font-family: ui-monospace, "SF Mono", "Cascadia Code", monospace; }
        p { margin: 6px 0; }
        blockquote { margin: 4px 0 12px; padding: 6px 12px;
                     background: #f8fafc; border-left: 3px solid #94a3b8;
                     color: #475569; font-style: normal; font-size: 12.5px; }
        code { font: 12px ui-monospace, "SF Mono", "Cascadia Code", monospace;
               background: #f1f5f9; padding: 1px 6px; border-radius: 4px;
               color: #0f172a; }
        h3 code { background: transparent; padding: 0; color: #1d4ed8; }
        table { border-collapse: collapse; width: 100%; margin: 8px 0 18px;
                font-size: 12.5px; }
        th, td { border: 1px solid #e5e7eb; padding: 6px 9px; text-align: left;
                 vertical-align: top; }
        th { background: #f8fafc; font-weight: 600; color: #334155;
             font-size: 11px; text-transform: uppercase; letter-spacing: .04em; }
        td code { font-size: 11.5px; }
        hr { border: 0; border-top: 1px solid #e5e7eb; margin: 32px 0; }
        em { color: #6366f1; font-style: normal; }
        strong { color: #0f172a; }

        @media print {
          body { margin: 0; padding: 12mm 14mm; max-width: none; }
          h2 { break-before: auto; break-after: avoid; }
          h3 { break-after: avoid; }
          table { break-inside: avoid; font-size: 11.5px; }
          tr { break-inside: avoid; }
        }
    """
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Beakon — Database Relationships</title>
<style>{css}</style>
</head>
<body>
{inner}
</body>
</html>
"""


if __name__ == "__main__":
    main()
