# Generated by Django 6.0.4 on 2026-04-17 17:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beakon_core', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_number_last4', models.CharField(blank=True, max_length=4)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_balance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='The cash COA row this bank feeds into. Must belong to the entity.', on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='beakon_core.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beakon_created_bank_accounts', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='beakon_core.entity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_bank_accounts', to='organizations.organization')),
            ],
            options={
                'db_table': 'beakon_bankaccount',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('csv', 'CSV'), ('ofx', 'OFX'), ('manual', 'Manual')], default='csv', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('duplicate_rows', models.IntegerField(default=0)),
                ('error_rows', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_imports', to='beakon_banking.bankaccount')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beakon_feed_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'beakon_feedimport',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='SHA1-based dedup key: (bank_account, date, amount, normalized desc).', max_length=128)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('original_description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=4, help_text='Signed: positive = deposit/credit from bank POV; negative = withdrawal.', max_digits=19)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('new', 'New'), ('proposed', 'Proposed'), ('matched', 'Matched'), ('ignored', 'Ignored')], default='new', max_length=20)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='beakon_banking.bankaccount')),
                ('proposed_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_bank_transactions', to='beakon_core.journalentry')),
                ('feed_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='beakon_banking.feedimport')),
            ],
            options={
                'db_table': 'beakon_banktransaction',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['organization', 'is_active'], name='beakon_bank_organiz_fe6933_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['entity'], name='beakon_bank_entity__2cabf9_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_account', 'date'], name='beakon_bank_bank_ac_fa4e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_account', 'status'], name='beakon_bank_bank_ac_16afe7_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['proposed_journal_entry'], name='beakon_bank_propose_e28ed5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='banktransaction',
            unique_together={('bank_account', 'external_id')},
        ),
    ]
