# Generated by Django 6.0.4 on 2026-05-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedimport',
            name='source',
            field=models.CharField(choices=[('csv', 'CSV'), ('ofx', 'OFX'), ('manual', 'Manual'), ('ai', 'AI Statement')], default='csv', max_length=20),
        ),
    ]
