# Generated by Django 6.0.4 on 2026-05-09 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_banking', '0002_alter_feedimport_source'),
        ('beakon_core', '0043_alter_sourcedocument_unique_together_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedimport',
            name='source',
            field=models.CharField(choices=[('csv', 'CSV'), ('ofx', 'OFX'), ('manual', 'Manual'), ('ai', 'AI Statement'), ('avaloq_sftp', 'Avaloq SFTP feed')], default='csv', max_length=20),
        ),
        migrations.CreateModel(
            name='AvaloqFeedDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text="Original zip filename, e.g. 'ABC123_2026-05-09.zip'.", max_length=255)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('business_date', models.DateField(help_text="The bank's stated reporting date (T-1 from delivery).")),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('ingest_started_at', models.DateTimeField(blank=True, null=True)),
                ('ingest_completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('ingesting', 'Ingesting'), ('ingested', 'Ingested'), ('failed', 'Failed')], default='received', max_length=16)),
                ('file_counts', models.JSONField(blank=True, default=dict, help_text="Per-file row counts after ingest, e.g. {'cash': 47, 'securities': 12, 'positions': 23, ...}.")),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('cash_feed_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaloq_drops_for_cash', to='beakon_banking.feedimport')),
                ('custodian', models.ForeignKey(blank=True, help_text="Bank / custodian that pushed this zip. May be null until we've onboarded the custodian master.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaloq_drops', to='beakon_core.custodian')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_avaloq_drops', to='organizations.organization')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beakon_avaloq_drops_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'beakon_avaloq_drop',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_type', models.CharField(choices=[('position_count_mismatch', 'Position count mismatch'), ('position_qty_mismatch', 'Position quantity mismatch'), ('unknown_isin', 'Unknown ISIN — no TaxLot'), ('missing_portfolio', 'Portfolio not found in Beakon'), ('fx_rate_missing', 'FX rate missing for currency')], max_length=40)),
                ('isin', models.CharField(blank=True, max_length=24)),
                ('bank_value', models.CharField(blank=True, help_text="What the bank reported (free-form string, e.g. '95' or 'USD 12,450').", max_length=120)),
                ('beakon_value', models.CharField(blank=True, max_length=120)),
                ('detail', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='beakon_banking.avaloqfeeddrop')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_breaks', to='beakon_core.portfolio')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beakon_breaks_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'beakon_recon_break',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='avaloqfeeddrop',
            index=models.Index(fields=['organization', 'business_date'], name='beakon_aval_organiz_e51317_idx'),
        ),
        migrations.AddIndex(
            model_name='avaloqfeeddrop',
            index=models.Index(fields=['organization', 'status'], name='beakon_aval_organiz_20f21c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='avaloqfeeddrop',
            unique_together={('organization', 'sha256', 'business_date')},
        ),
        migrations.AddIndex(
            model_name='reconciliationbreak',
            index=models.Index(fields=['drop', 'resolved'], name='beakon_reco_drop_id_29c5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationbreak',
            index=models.Index(fields=['portfolio', 'resolved'], name='beakon_reco_portfol_8b4163_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationbreak',
            index=models.Index(fields=['break_type'], name='beakon_reco_break_t_10eca2_idx'),
        ),
    ]
