# Generated by Django 6.0.4 on 2026-05-09 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_banking', '0003_alter_feedimport_source_avaloqfeeddrop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaloqfeeddrop',
            name='file_size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avaloqfeeddrop',
            name='prior_drop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_drops', to='beakon_banking.avaloqfeeddrop'),
        ),
        migrations.AddField(
            model_name='avaloqfeeddrop',
            name='reprocessed_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprocessed_attempts', to='beakon_banking.avaloqfeeddrop'),
        ),
        migrations.AddField(
            model_name='avaloqfeeddrop',
            name='schema_version',
            field=models.CharField(blank=True, help_text="Detected statement schema version (e.g. 'avaloq-v1'). A change here without prior coordination is itself a break.", max_length=20),
        ),
        migrations.AddField(
            model_name='avaloqfeeddrop',
            name='source_ip',
            field=models.CharField(blank=True, help_text='Connecting IP. In production set by the SFTP daemon; in demo the API view fakes it from a configured allowlist.', max_length=45),
        ),
        migrations.AddField(
            model_name='reconciliationbreak',
            name='category',
            field=models.CharField(choices=[('timing', 'Timing — likely resolves by T+2'), ('fx', 'FX — rate / valuation differential'), ('missing_trade', 'Missing trade — no record in ledger'), ('corp_action', 'Corporate action — split / dividend'), ('true_error', 'True error — investigate'), ('unknown', 'Unknown — needs human review')], default='unknown', help_text='Auto-classified reason. Drives UI grouping + suggested resolution.', max_length=20),
        ),
        migrations.AddField(
            model_name='reconciliationbreak',
            name='suggested_resolution',
            field=models.TextField(blank=True, help_text='Engine-generated next-step suggestion shown to the operator.'),
        ),
    ]
