# Generated by Django 6.0.4 on 2026-05-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_banking', '0004_avaloqfeeddrop_file_size_bytes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaloqfeeddrop',
            name='archive_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
