# Generated by Django 6.0.4 on 2026-04-17 16:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 code, e.g. USD, EUR.', max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('decimal_places', models.IntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'beakon_currency',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_account_groups', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='beakon_core.accountgroup')),
            ],
            options={
                'db_table': 'beakon_accountgroup',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code (unique within the organization). E.g. HOLDCO, TRUST-01.', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('entity_type', models.CharField(choices=[('company', 'Company'), ('trust', 'Trust'), ('foundation', 'Foundation'), ('partnership', 'Partnership'), ('individual', 'Individual'), ('fund', 'Fund'), ('branch', 'Branch'), ('other', 'Other')], default='company', max_length=20)),
                ('functional_currency', models.CharField(default='USD', help_text="Currency in which this entity's books are kept and reported.", max_length=3)),
                ('reporting_currency', models.CharField(blank=True, help_text='Optional presentation currency for consolidated reporting. Blank = same as functional_currency.', max_length=3)),
                ('country', models.CharField(default='US', max_length=2)),
                ('fiscal_year_start_month', models.IntegerField(default=1, help_text='Month (1–12) in which the fiscal year starts.')),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entities', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='beakon_core.entity')),
            ],
            options={
                'db_table': 'beakon_entity',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('account_subtype', models.CharField(blank=True, choices=[('bank', 'Bank'), ('cash', 'Cash on Hand'), ('current_asset', 'Current Asset'), ('accounts_receivable', 'Accounts Receivable'), ('intercompany_receivable', 'Intercompany Receivable (Due From)'), ('prepaid', 'Prepaid Expenses'), ('inventory', 'Inventory'), ('investment', 'Investment'), ('loan_receivable', 'Loan Receivable'), ('fixed_asset', 'Fixed Asset'), ('accumulated_depreciation', 'Accumulated Depreciation'), ('intangible_asset', 'Intangible Asset'), ('other_asset', 'Other Asset'), ('accounts_payable', 'Accounts Payable'), ('intercompany_payable', 'Intercompany Payable (Due To)'), ('accrued_liability', 'Accrued Liability'), ('current_liability', 'Current Liability'), ('loan_payable', 'Loan Payable'), ('long_term_liability', 'Long-Term Liability'), ('tax_payable', 'Tax Payable'), ('vat_payable', 'VAT Payable'), ('other_liability', 'Other Liability'), ('capital', 'Capital / Contributed'), ('retained_earnings', 'Retained Earnings'), ('revaluation_reserve', 'Revaluation Reserve'), ('fx_translation_reserve', 'FX Translation Reserve'), ('distribution', "Distribution / Owner's Draw"), ('other_equity', 'Other Equity'), ('operating_revenue', 'Operating Revenue'), ('investment_income', 'Investment Income'), ('fx_gain', 'FX Gain'), ('other_income', 'Other Income'), ('cogs', 'Cost of Goods Sold'), ('operating_expense', 'Operating Expense'), ('professional_fees', 'Professional Fees'), ('depreciation', 'Depreciation'), ('fx_loss', 'FX Loss'), ('tax_expense', 'Tax Expense'), ('other_expense', 'Other Expense')], max_length=50)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=6)),
                ('currency', models.CharField(blank=True, help_text='Blank = multi-currency account. A fixed currency restricts journal lines against this account to that currency.', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System accounts (AP, AR, retained earnings, FX gain/loss) cannot be deleted and usually cannot be posted to directly.')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_accounts', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='beakon_core.account')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='beakon_core.accountgroup')),
                ('entity', models.ForeignKey(blank=True, help_text='Optional. NULL = shared across every entity in the organization.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='beakon_core.entity')),
            ],
            options={
                'db_table': 'beakon_account',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FXRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=10, help_text='How many units of to_currency = 1 unit of from_currency.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('as_of', models.DateField()),
                ('source', models.CharField(blank=True, help_text='Where this rate came from: manual / ecb / openexchange / etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'beakon_fxrate',
                'ordering': ['-as_of'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency', '-as_of'], name='beakon_fxra_from_cu_6f46fd_idx')],
                'unique_together': {('from_currency', 'to_currency', 'as_of')},
            },
        ),
        migrations.CreateModel(
            name='IntercompanyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Optional external reference — invoice number, wire ID, etc.', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intercompany_groups', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercompany_groups', to='organizations.organization')),
            ],
            options={
                'db_table': 'beakon_intercompanygroup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(help_text='Auto-assigned per-entity sequence (e.g. JE-000001).', max_length=50)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('memo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('source_type', models.CharField(choices=[('manual', 'Manual Entry'), ('bill', 'Bill'), ('bill_payment', 'Bill Payment'), ('invoice', 'Invoice'), ('invoice_payment', 'Invoice Payment'), ('bank_transaction', 'Bank Transaction'), ('intercompany', 'Intercompany'), ('opening_balance', 'Opening Balance'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal'), ('fx_revaluation', 'FX Revaluation')], default='manual', max_length=50)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_debit_functional', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('total_credit_functional', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('submitted_for_approval_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beakon_approved_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('counterparty_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_journal_entries', to='beakon_core.entity')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beakon_created_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='beakon_core.entity')),
                ('intercompany_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='beakon_core.intercompanygroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_journal_entries', to='organizations.organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beakon_posted_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beakon_rejected_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='beakon_core.journalentry')),
                ('submitted_for_approval_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beakon_submitted_journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'beakon_journalentry',
                'ordering': ['-date', '-entry_number'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted for approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned_to_draft', 'Returned to draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], max_length=30)),
                ('from_status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted'), ('reversed', 'Reversed')], max_length=20)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted'), ('reversed', 'Reversed')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to='beakon_core.journalentry')),
            ],
            options={
                'db_table': 'beakon_approvalaction',
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('debit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=10, default=Decimal('1'), help_text='Units of functional per unit of transaction currency.', max_digits=20)),
                ('functional_debit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('functional_credit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('line_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='beakon_core.account')),
                ('counterparty_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_journal_lines', to='beakon_core.entity')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='beakon_core.journalentry')),
            ],
            options={
                'db_table': 'beakon_journalline',
                'ordering': ['line_order'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human label, e.g. 'April 2026'.", max_length=100)),
                ('period_type', models.CharField(choices=[('month', 'Month'), ('quarter', 'Quarter'), ('year', 'Year')], default='month', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('soft_close', 'Soft Close'), ('closed', 'Closed')], default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beakon_closed_periods', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='beakon_core.entity')),
            ],
            options={
                'db_table': 'beakon_period',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='beakon_core.period'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['organization', 'is_active'], name='beakon_enti_organiz_e14f47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['organization', 'account_type'], name='beakon_acco_organiz_a5e9a0_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['organization', 'entity', 'is_active'], name='beakon_acco_organiz_51bdb0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('organization', 'entity', 'code')},
        ),
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['journal_entry', 'at'], name='beakon_appr_journal_e90195_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['journal_entry'], name='beakon_jour_journal_2b7e94_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account'], name='beakon_jour_account_5a0711_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0)), name='beakon_jl_debit_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', 0)), name='beakon_jl_credit_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='beakon_jl_not_both_sides'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _connector='OR'), name='beakon_jl_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='beakon_jl_positive_rate'),
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['entity', 'status'], name='beakon_peri_entity__d2bc42_idx'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='beakon_period_dates_ordered'),
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('entity', 'start_date', 'end_date')},
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'date'], name='beakon_jour_organiz_e6d6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entity', 'date'], name='beakon_jour_entity__964e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'status'], name='beakon_jour_organiz_17299f_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_type', 'source_id'], name='beakon_jour_source__29f408_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['intercompany_group'], name='beakon_jour_interco_24f31c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('entity', 'entry_number')},
        ),
    ]
