# Generated by Django 6.0.4 on 2026-04-19 13:14

import beakon_core.models.documents
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=beakon_core.models.documents._upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_hash', models.CharField(help_text='SHA-256 hex digest of the file bytes — used for dedup.', max_length=64)),
                ('content_type', models.CharField(help_text='MIME type validated by SourceDocumentService.attach().', max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beakon_deleted_documents', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='beakon_core.journalentry')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beakon_uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'beakon_sourcedocument',
                'ordering': ['uploaded_at'],
                'indexes': [models.Index(fields=['journal_entry', 'is_deleted'], name='beakon_sour_journal_0fc906_idx'), models.Index(fields=['content_hash'], name='beakon_sour_content_345a34_idx')],
                'unique_together': {('journal_entry', 'content_hash')},
            },
        ),
    ]
