# Generated by Django 6.0.4 on 2026-04-20 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0002_sourcedocument'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short identifier, unique per organization (e.g. STAPLES, ACME-INC).', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, help_text='EIN, VAT number, etc. Kept as free text for multi-jurisdiction flexibility.', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, help_text='ISO 3166 alpha-2.', max_length=2)),
                ('default_currency', models.CharField(blank=True, help_text="ISO 4217. Blank = falls back to the entity's functional currency.", max_length=3)),
                ('default_payment_terms_days', models.PositiveIntegerField(default=30, help_text='Net days for bills (vendor) or invoices (customer).')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Optional cap on outstanding AR. Informational in v1.', max_digits=19, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('default_revenue_account', models.ForeignKey(blank=True, help_text='Pre-fills the credit line on invoices to this customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_customers', to='beakon_core.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'beakon_customer',
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='beakon_core.customer'),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short identifier, unique per organization (e.g. STAPLES, ACME-INC).', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, help_text='EIN, VAT number, etc. Kept as free text for multi-jurisdiction flexibility.', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, help_text='ISO 3166 alpha-2.', max_length=2)),
                ('default_currency', models.CharField(blank=True, help_text="ISO 4217. Blank = falls back to the entity's functional currency.", max_length=3)),
                ('default_payment_terms_days', models.PositiveIntegerField(default=30, help_text='Net days for bills (vendor) or invoices (customer).')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_details', models.TextField(blank=True, help_text='Remittance instructions, IBAN/SWIFT, etc. Kept as free text.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('default_expense_account', models.ForeignKey(blank=True, help_text='Pre-fills the debit line on bills from this vendor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_vendors', to='beakon_core.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'beakon_vendor',
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='beakon_core.vendor'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'is_active'], name='beakon_cust_organiz_d434dd_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'name'], name='beakon_cust_organiz_a2f681_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['organization', 'is_active'], name='beakon_vend_organiz_4a1b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['organization', 'name'], name='beakon_vend_organiz_11b3b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('organization', 'code')},
        ),
    ]
