# Generated by Django 6.0.4 on 2026-04-20 15:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0003_customer_journalentry_customer_vendor_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Auto-assigned BILL-NNNNNN per organization.', max_length=50)),
                ('bill_number', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total', models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Wire ref, check number, or similar.', max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accrual_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_as_accrual', to='beakon_core.journalentry')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_approved', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='beakon_core.entity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='organizations.organization')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_paid', to=settings.AUTH_USER_MODEL)),
                ('payment_bank_account', models.ForeignKey(blank=True, help_text='Cash / bank account the payment was drawn from.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills_paid_from', to='beakon_core.account')),
                ('payment_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_as_payment', to='beakon_core.journalentry')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_rejected', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_submitted', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='beakon_core.vendor')),
            ],
            options={
                'db_table': 'beakon_bill',
                'ordering': ['-invoice_date', '-reference'],
            },
        ),
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount', models.DecimalField(decimal_places=4, help_text='Pre-tax amount for this line (= quantity × unit_price, usually).', max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_order', models.IntegerField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='beakon_core.bill')),
                ('expense_account', models.ForeignKey(help_text='The account that will be DEBITED on the accrual JE.', on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='beakon_core.account')),
            ],
            options={
                'db_table': 'beakon_billline',
                'ordering': ['line_order'],
            },
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['organization', 'status'], name='beakon_bill_organiz_43e203_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['vendor', 'status'], name='beakon_bill_vendor__4e3b99_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['entity', 'status'], name='beakon_bill_entity__4a9a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['due_date'], name='beakon_bill_due_dat_f6d910_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('organization', 'reference')},
        ),
        migrations.AddIndex(
            model_name='billline',
            index=models.Index(fields=['bill'], name='beakon_bill_bill_id_b19510_idx'),
        ),
        migrations.AddIndex(
            model_name='billline',
            index=models.Index(fields=['expense_account'], name='beakon_bill_expense_5eef0a_idx'),
        ),
    ]
