# Generated by Django 6.0.4 on 2026-04-20 15:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0004_bill_billline_bill_beakon_bill_organiz_43e203_idx_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Auto-assigned INV-NNNNNN per organization.', max_length=50)),
                ('invoice_number', models.CharField(blank=True, help_text='Customer-facing invoice number; defaults to reference if blank.', max_length=100)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total', models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('issued', 'Issued'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='beakon_core.customer')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='beakon_core.entity')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_issued', to=settings.AUTH_USER_MODEL)),
                ('issued_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoiced_as_issuance', to='beakon_core.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.organization')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_paid', to=settings.AUTH_USER_MODEL)),
                ('payment_bank_account', models.ForeignKey(blank=True, help_text='Cash / bank account the receipt landed in.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_received_into', to='beakon_core.account')),
                ('payment_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoiced_as_payment', to='beakon_core.journalentry')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_rejected', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'beakon_invoice',
                'ordering': ['-invoice_date', '-reference'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount', models.DecimalField(decimal_places=4, help_text='Pre-tax amount for this line.', max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_order', models.IntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='beakon_core.invoice')),
                ('revenue_account', models.ForeignKey(help_text='The account that will be CREDITED on the issuance JE.', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='beakon_core.account')),
            ],
            options={
                'db_table': 'beakon_invoiceline',
                'ordering': ['line_order'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status'], name='beakon_invo_organiz_ce6e48_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'status'], name='beakon_invo_custome_7bcf59_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['entity', 'status'], name='beakon_invo_entity__f951b7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='beakon_invo_due_dat_b2a25b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('organization', 'reference')},
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice'], name='beakon_invo_invoice_e63ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['revenue_account'], name='beakon_invo_revenue_f5a377_idx'),
        ),
    ]
