# Generated by Django 6.0.4 on 2026-04-23 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0005_invoice_invoiceline_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_subtype',
            field=models.CharField(blank=True, help_text='Built-in subtype (see constants.ACCOUNT_SUBTYPE_CHOICES) or an org-defined CustomAccountSubtype value.', max_length=50),
        ),
        migrations.CreateModel(
            name='CustomAccountSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('value', models.SlugField()),
                ('label', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_account_subtypes', to='organizations.organization')),
            ],
            options={
                'db_table': 'beakon_custom_account_subtype',
                'ordering': ['account_type', 'label'],
                'unique_together': {('organization', 'value')},
            },
        ),
    ]
