# Generated by Django 6.0.4 on 2026-04-25 16:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0010_entity_accounting_standard'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoAMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_id', models.CharField(max_length=80)),
                ('source_account_no', models.CharField(max_length=20)),
                ('source_account_name', models.CharField(blank=True, max_length=255)),
                ('universal_coa_code', models.CharField(max_length=80)),
                ('universal_coa_name', models.CharField(blank=True, max_length=255)),
                ('mapping_type', models.CharField(blank=True, max_length=30)),
                ('mapping_percent', models.DecimalField(decimal_places=4, default=Decimal('100'), max_digits=7)),
                ('condition_rule', models.CharField(blank=True, max_length=255)),
                ('required_dimension', models.CharField(blank=True, max_length=255)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('review_status', models.CharField(blank=True, max_length=30)),
                ('approved_by', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('workbook_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beakon_coa_mapping',
                'ordering': ['source_account_no', 'mapping_id'],
            },
        ),
        migrations.CreateModel(
            name='ControlledListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=100)),
                ('list_code', models.CharField(max_length=80)),
                ('list_value', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('active_flag', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beakon_controlled_list_entry',
                'ordering': ['list_name', 'display_order', 'list_value'],
            },
        ),
        migrations.CreateModel(
            name='DimensionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('applies_to', models.CharField(blank=True, max_length=255)),
                ('mandatory_flag', models.BooleanField(default=False)),
                ('multi_select_allowed', models.BooleanField(default=False)),
                ('master_data_owner', models.CharField(blank=True, max_length=120)),
                ('hierarchy_allowed', models.BooleanField(default=False)),
                ('active_flag', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('workbook_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beakon_dimension_type',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DimensionValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=80)),
                ('account_no', models.CharField(max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('rule_type', models.CharField(blank=True, max_length=40)),
                ('trigger_event', models.CharField(blank=True, max_length=40)),
                ('required_dimension_type_codes', models.CharField(blank=True, max_length=255)),
                ('optional_dimension_type_codes', models.CharField(blank=True, max_length=255)),
                ('conditional_dimension_type_codes', models.CharField(blank=True, max_length=255)),
                ('condition_expression', models.TextField(blank=True)),
                ('validation_error_message', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('master_driver', models.CharField(blank=True, max_length=80)),
                ('active_flag', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('workbook_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beakon_dimension_validation_rule',
                'ordering': ['account_no', 'rule_id'],
            },
        ),
        migrations.CreateModel(
            name='DimensionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('parent_value_code', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('active_flag', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('workbook_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beakon_dimension_value',
                'ordering': ['dimension_type__code', 'code'],
            },
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='beakon_acco_organiz_431fdc_idx',
            old_name='beakon_acc_organiz_c6bce3_idx',
        ),
        migrations.RenameIndex(
            model_name='coadefinition',
            new_name='beakon_coa__organiz_eb6e42_idx',
            old_name='beakon_coa_organiz_2b2c34_idx',
        ),
        migrations.RenameIndex(
            model_name='coadefinition',
            new_name='beakon_coa__organiz_778704_idx',
            old_name='beakon_coa_organiz_1451a2_idx',
        ),
        migrations.RenameIndex(
            model_name='journalline',
            new_name='beakon_jour_journal_ffa2a5_idx',
            old_name='beakon_jou_journal_cf9719_idx',
        ),
        migrations.RenameIndex(
            model_name='journalline',
            new_name='beakon_jour_journal_8e1acf_idx',
            old_name='beakon_jou_journal_01fdfd_idx',
        ),
        migrations.RenameIndex(
            model_name='journalline',
            new_name='beakon_jour_journal_dc2d62_idx',
            old_name='beakon_jou_journal_93ba3c_idx',
        ),
        migrations.RenameIndex(
            model_name='journalline',
            new_name='beakon_jour_journal_3c50e7_idx',
            old_name='beakon_jou_journal_370f97_idx',
        ),
        migrations.AddField(
            model_name='account',
            name='cashflow_category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='account',
            name='default_universal_coa_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='account',
            name='dimension_validation_rule',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='fx_revalue_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='header_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='level_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='mandatory_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='mapping_method',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='monetary_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='optional_dimension_type_codes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='posting_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='report_group',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='account',
            name='required_dimension_type_codes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='scope',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='short_name',
            field=models.CharField(blank=True, help_text='Workbook Short_Name from 02 CoA Master, when imported.', max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='source_account_type',
            field=models.CharField(blank=True, help_text='Raw workbook Account_Type, e.g. HEADER, ASSET, INCOME, MEMO.', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='tax_relevant_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='universal_map_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='workbook_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional workbook columns preserved for later phases.'),
        ),
        migrations.AddField(
            model_name='coamapping',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universal_mappings', to='beakon_core.account'),
        ),
        migrations.AddField(
            model_name='coamapping',
            name='coa_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='beakon_core.coadefinition'),
        ),
        migrations.AddField(
            model_name='coamapping',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_coa_mappings', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='controlledlistentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_controlled_list_entries', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='dimensiontype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_dimension_types', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='dimensionvalidationrule',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dimension_validation_rules', to='beakon_core.account'),
        ),
        migrations.AddField(
            model_name='dimensionvalidationrule',
            name='coa_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_rules', to='beakon_core.coadefinition'),
        ),
        migrations.AddField(
            model_name='dimensionvalidationrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_dimension_validation_rules', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='dimensionvalue',
            name='dimension_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='beakon_core.dimensiontype'),
        ),
        migrations.AddField(
            model_name='dimensionvalue',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_dimension_values', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='coamapping',
            index=models.Index(fields=['organization', 'coa_definition'], name='beakon_coa__organiz_00e83e_idx'),
        ),
        migrations.AddIndex(
            model_name='coamapping',
            index=models.Index(fields=['organization', 'universal_coa_code'], name='beakon_coa__organiz_c9b840_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coamapping',
            unique_together={('organization', 'mapping_id')},
        ),
        migrations.AddIndex(
            model_name='controlledlistentry',
            index=models.Index(fields=['organization', 'list_name', 'active_flag'], name='beakon_cont_organiz_060412_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='controlledlistentry',
            unique_together={('organization', 'list_name', 'list_code')},
        ),
        migrations.AddIndex(
            model_name='dimensiontype',
            index=models.Index(fields=['organization', 'active_flag'], name='beakon_dime_organiz_cc33bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dimensiontype',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='dimensionvalidationrule',
            index=models.Index(fields=['organization', 'coa_definition'], name='beakon_dime_organiz_8beeff_idx'),
        ),
        migrations.AddIndex(
            model_name='dimensionvalidationrule',
            index=models.Index(fields=['organization', 'account'], name='beakon_dime_organiz_d373c7_idx'),
        ),
        migrations.AddIndex(
            model_name='dimensionvalidationrule',
            index=models.Index(fields=['organization', 'active_flag'], name='beakon_dime_organiz_208170_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dimensionvalidationrule',
            unique_together={('organization', 'rule_id')},
        ),
        migrations.AddIndex(
            model_name='dimensionvalue',
            index=models.Index(fields=['organization', 'active_flag'], name='beakon_dime_organiz_b11aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='dimensionvalue',
            index=models.Index(fields=['organization', 'code'], name='beakon_dime_organiz_9084fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dimensionvalue',
            unique_together={('organization', 'dimension_type', 'code')},
        ),
    ]
