# Generated by Django 6.0.4 on 2026-04-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0011_coamapping_controlledlistentry_dimensiontype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cashflow_category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='account',
            name='default_universal_coa_code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='account',
            name='mapping_method',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='account',
            name='report_group',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
