# Generated by Django 6.0.4 on 2026-04-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0012_alter_account_cashflow_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensionvalidationrule',
            name='master_driver',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='dimensionvalidationrule',
            name='rule_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='dimensionvalidationrule',
            name='severity',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='dimensionvalidationrule',
            name='trigger_event',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
