# Generated by Django 6.0.4 on 2026-05-01 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0013_alter_dimensionvalidationrule_master_driver_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_lot_id', models.CharField(help_text='Stable workbook identifier, e.g. TLOT_EQ_0001.', max_length=80)),
                ('instrument_code', models.CharField(blank=True, help_text='Workbook Instrument_ID. FK to Instrument once that master exists.', max_length=80)),
                ('portfolio_code', models.CharField(blank=True, help_text='Workbook Portfolio_ID. FK to Portfolio once that master exists.', max_length=80)),
                ('custodian_code', models.CharField(blank=True, help_text='Workbook Custodian_ID. FK to Custodian once that master exists.', max_length=80)),
                ('account_no', models.CharField(blank=True, help_text='Raw workbook Account_No, kept for round-trip safety.', max_length=20)),
                ('lot_open_date', models.DateField(blank=True, null=True)),
                ('acquisition_trade_date', models.DateField(blank=True, null=True)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('original_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('remaining_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('unit_of_measure', models.CharField(blank=True, help_text='e.g. SHARES, KG, OZ, UNITS.', max_length=20)),
                ('acquisition_price_per_unit', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('acquisition_currency', models.CharField(blank=True, max_length=3)),
                ('acquisition_fx_rate_to_reporting', models.DecimalField(blank=True, decimal_places=10, help_text='FX rate at acquisition into the reporting currency.', max_digits=20, null=True)),
                ('acquisition_cost_transaction_ccy', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('acquisition_cost_reporting_ccy', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('cost_basis_method', models.CharField(choices=[('FIFO', 'FIFO — first in, first out'), ('LIFO', 'LIFO — last in, first out'), ('AVERAGE', 'Average cost'), ('SPECIFIC_ID', 'Specific identification'), ('HIFO', 'HIFO — highest in, first out')], default='FIFO', max_length=20)),
                ('lot_status', models.CharField(choices=[('OPEN', 'Open — no disposals yet'), ('PARTIAL', 'Partial — some quantity disposed'), ('CLOSED', 'Closed — fully disposed')], default='OPEN', max_length=12)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposed_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('cumulative_disposed_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('remaining_cost_reporting_ccy', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('realized_gain_loss_reporting_ccy', models.DecimalField(decimal_places=4, default=0, max_digits=24)),
                ('wash_sale_flag', models.BooleanField(default=False)),
                ('corporate_action_adjusted_flag', models.BooleanField(default=False)),
                ('active_flag', models.BooleanField(default=True)),
                ('source_transaction_reference', models.CharField(blank=True, max_length=120)),
                ('source_document_reference', models.CharField(blank=True, help_text='Workbook reference. May later FK to SourceDocument.', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('workbook_metadata', models.JSONField(blank=True, default=dict, help_text='Any workbook columns not yet promoted to a dedicated DB field.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, help_text='GL account this lot posts against (workbook Account_No).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_lots', to='beakon_core.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_tax_lots', to='organizations.organization')),
            ],
            options={
                'db_table': 'beakon_tax_lot',
                'ordering': ['tax_lot_id'],
                'indexes': [models.Index(fields=['organization', 'instrument_code'], name='beakon_tax__organiz_2b3f42_idx'), models.Index(fields=['organization', 'portfolio_code'], name='beakon_tax__organiz_2529e0_idx'), models.Index(fields=['organization', 'custodian_code'], name='beakon_tax__organiz_5e84a1_idx'), models.Index(fields=['organization', 'lot_status'], name='beakon_tax__organiz_0c90de_idx'), models.Index(fields=['organization', 'account'], name='beakon_tax__organiz_c0973b_idx')],
                'unique_together': {('organization', 'tax_lot_id')},
            },
        ),
    ]
