# Generated by Django 6.0.4 on 2026-05-01 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0014_taxlot'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='is_rebillable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalline',
            name='rebill_client_dimension_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebillable_lines', to='beakon_core.dimensionvalue'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['journal_entry', 'is_rebillable'], name='beakon_jour_journal_1bd4d1_idx'),
        ),
    ]
