# Generated by Django 6.0.4 on 2026-05-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0015_journalline_is_rebillable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxlot',
            name='lot_status',
            field=models.CharField(choices=[('OPEN', 'Open — no disposals yet'), ('PARTIALLY_DISPOSED', 'Partially disposed — some quantity sold'), ('CLOSED', 'Closed — fully disposed')], default='OPEN', max_length=24),
        ),
    ]
