# Generated by Django 6.0.4 on 2026-05-01 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0016_alter_taxlot_lot_status'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(help_text='Stable workbook identifier, e.g. LOAN_LMB_001.', max_length=80)),
                ('loan_name', models.CharField(blank=True, max_length=255)),
                ('loan_type', models.CharField(blank=True, choices=[('LOMBARD', 'Lombard / margin facility'), ('MORTGAGE', 'Mortgage'), ('PRIVATE_LOAN', 'Private loan'), ('RELATED_PARTY_LOAN', 'Related-party loan'), ('CONVERTIBLE_LOAN', 'Convertible loan / note'), ('CREDIT_LINE', 'Credit line / revolver')], max_length=24)),
                ('loan_side', models.CharField(blank=True, choices=[('ASSET', 'Asset — Beakon entity is the lender'), ('LIABILITY', 'Liability — Beakon entity is the borrower')], max_length=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MATURED', 'Matured'), ('REPAID', 'Repaid'), ('DEFAULTED', 'Defaulted'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=16)),
                ('borrower_or_lender_code', models.CharField(blank=True, help_text='Counterparty or RelatedParty code. FK once those masters exist.', max_length=80)),
                ('related_party_flag', models.BooleanField(default=False)),
                ('facility_reference', models.CharField(blank=True, max_length=80)),
                ('internal_reference', models.CharField(blank=True, max_length=80)),
                ('loan_currency', models.CharField(blank=True, help_text='Workbook value, e.g. CCY_CHF / CCY_USD. Engine strips the prefix.', max_length=10)),
                ('principal_original', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('current_principal_outstanding', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('interest_rate_type', models.CharField(blank=True, choices=[('FIXED', 'Fixed rate'), ('FLOATING', 'Floating rate')], max_length=12)),
                ('fixed_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Annual fixed rate, e.g. 1.85 = 1.85%.', max_digits=10, null=True)),
                ('reference_rate_code', models.CharField(blank=True, help_text='Floating reference rate, e.g. SARON, SOFR, EURIBOR_3M.', max_length=24)),
                ('spread_bps', models.CharField(blank=True, help_text='Basis-point spread over the reference rate. Stored as text until Thomas fixes the workbook (column was Excel-coerced into dates).', max_length=40)),
                ('interest_reset_frequency', models.CharField(blank=True, max_length=20)),
                ('interest_payment_frequency', models.CharField(blank=True, max_length=20)),
                ('day_count_convention', models.CharField(blank=True, help_text='Workbook codes: 30_360 / ACT_360 / ACT_365 / ACT_ACT.', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('first_accrual_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('next_reset_date', models.DateField(blank=True, null=True)),
                ('next_interest_payment_date', models.DateField(blank=True, null=True)),
                ('next_principal_payment_date', models.DateField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('repayment_type', models.CharField(blank=True, choices=[('AMORTIZING', 'Amortizing'), ('BULLET', 'Bullet'), ('REVOLVING', 'Revolving')], max_length=16)),
                ('amortization_method', models.CharField(blank=True, help_text='EFFECTIVE_INTEREST / LEVEL_PAYMENT / STRAIGHT_LINE / NA.', max_length=24)),
                ('bullet_flag', models.BooleanField(default=False)),
                ('scheduled_principal_amount', models.CharField(blank=True, help_text='Stored as text until workbook column is cleaned (Excel coerced numeric values to dates).', max_length=40)),
                ('prepayment_allowed_flag', models.BooleanField(default=False)),
                ('capitalized_interest_flag', models.BooleanField(default=False)),
                ('reporting_portfolio_code', models.CharField(blank=True, help_text='Workbook Portfolio code. FK to Portfolio once that master exists.', max_length=80)),
                ('collateral_link_type', models.CharField(blank=True, help_text='BANK / CUSTODY_POOL / PROPERTY / RELATED_PARTY / NONE.', max_length=24)),
                ('collateral_link_id', models.CharField(blank=True, help_text='Polymorphic ref into the master named by collateral_link_type.', max_length=80)),
                ('current_noncurrent_split_method', models.CharField(blank=True, max_length=32)),
                ('valuation_basis', models.CharField(blank=True, help_text='AMORTIZED_COST / FAIR_VALUE.', max_length=24)),
                ('impairment_method', models.CharField(blank=True, max_length=32)),
                ('accrual_required_flag', models.BooleanField(default=False)),
                ('fx_remeasure_flag', models.BooleanField(default=False)),
                ('default_principal_account_code', models.CharField(blank=True, max_length=20)),
                ('default_interest_income_account_code', models.CharField(blank=True, max_length=20)),
                ('default_interest_expense_account_code', models.CharField(blank=True, max_length=20)),
                ('default_fx_gain_loss_account_code', models.CharField(blank=True, help_text='Workbook code, may need cleanup (column was Excel-coerced).', max_length=40)),
                ('approval_required_flag', models.BooleanField(default=True)),
                ('manual_override_allowed_flag', models.BooleanField(default=False)),
                ('source_document_required_flag', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('workbook_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_fx_gain_loss_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_default_fx_gain_loss', to='beakon_core.account')),
                ('default_interest_expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_default_interest_expense', to='beakon_core.account')),
                ('default_interest_income_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_default_interest_income', to='beakon_core.account')),
                ('default_principal_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_default_principal', to='beakon_core.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_loans', to='organizations.organization')),
            ],
            options={
                'db_table': 'beakon_loan',
                'ordering': ['loan_id'],
                'indexes': [models.Index(fields=['organization', 'loan_type'], name='beakon_loan_organiz_62f3f6_idx'), models.Index(fields=['organization', 'loan_side'], name='beakon_loan_organiz_851b2b_idx'), models.Index(fields=['organization', 'status'], name='beakon_loan_organiz_396512_idx'), models.Index(fields=['organization', 'borrower_or_lender_code'], name='beakon_loan_organiz_533794_idx'), models.Index(fields=['organization', 'maturity_date'], name='beakon_loan_organiz_df3eb7_idx')],
                'unique_together': {('organization', 'loan_id')},
            },
        ),
    ]
