# Generated by Django 6.0.4 on 2026-05-01 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0017_loan'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.CharField(help_text='Stable workbook identifier, e.g. INS_LISTED_EQ_001.', max_length=80)),
                ('instrument_name', models.CharField(blank=True, max_length=255)),
                ('instrument_type', models.CharField(blank=True, help_text='Workbook code, e.g. LISTED_EQUITY, GOV_BOND, ETF, PE_FUND, CRYPTO.', max_length=40)),
                ('quoted_unquoted_flag', models.CharField(blank=True, choices=[('QUOTED', 'Quoted / listed'), ('UNQUOTED', 'Unquoted / private')], max_length=10)),
                ('asset_class_code', models.CharField(blank=True, help_text='ACL_* code from dimension values.', max_length=40)),
                ('strategy_code', models.CharField(blank=True, help_text='STR_* code from dimension values.', max_length=40)),
                ('portfolio_default', models.CharField(blank=True, help_text='PORT_* code; FK to Portfolio later.', max_length=40)),
                ('custodian_default', models.CharField(blank=True, help_text='CUST_* code; FK to Custodian later.', max_length=40)),
                ('issuer_or_counterparty_code', models.CharField(blank=True, help_text='Issuer code (CP_*) or related-party (RP_*); FK once those masters exist.', max_length=80)),
                ('related_party_flag', models.BooleanField(default=False)),
                ('isin_or_ticker', models.CharField(blank=True, max_length=64)),
                ('internal_reference', models.CharField(blank=True, max_length=80)),
                ('currency', models.CharField(blank=True, help_text='Workbook code, e.g. CCY_CHF / CCY_USD.', max_length=10)),
                ('jurisdiction_code', models.CharField(blank=True, max_length=20)),
                ('domicile_code', models.CharField(blank=True, max_length=20)),
                ('commitment_flag', models.BooleanField(default=False)),
                ('commitment_code', models.CharField(blank=True, help_text='COM_* code; FK to Commitment master later.', max_length=40)),
                ('loan_linked_flag', models.BooleanField(default=False)),
                ('loan_workbook_id', models.CharField(blank=True, help_text='Workbook Loan_ID. Resolved to the loan FK at import time.', max_length=80)),
                ('tax_lot_required', models.BooleanField(default=False)),
                ('income_type', models.CharField(blank=True, choices=[('DIVIDEND', 'Dividend'), ('COUPON', 'Coupon'), ('DISTRIBUTION', 'Distribution'), ('RENTAL', 'Rental'), ('OTHER', 'Other'), ('NONE', 'None')], max_length=20)),
                ('income_frequency', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMI_ANNUAL', 'Semi-annual'), ('ANNUAL', 'Annual'), ('AD_HOC', 'Ad hoc'), ('NONE', 'None')], max_length=20)),
                ('valuation_method', models.CharField(blank=True, choices=[('FVPL', 'Fair value through P&L'), ('FAIR_VALUE', 'Fair value (other)'), ('AMORTIZED_COST', 'Amortized cost'), ('HISTORICAL', 'Historical cost')], max_length=20)),
                ('price_source', models.CharField(blank=True, choices=[('MARKET_PRICE', 'Market price'), ('EXCHANGE_PRICE', 'Exchange price'), ('MANAGER_STATEMENT', 'Manager statement'), ('APPRAISAL', 'Appraisal')], max_length=24)),
                ('fx_exposure_flag', models.BooleanField(default=False)),
                ('impairment_method', models.CharField(blank=True, choices=[('NA', 'Not applicable'), ('SIMPLE_IMPAIRMENT', 'Simple impairment'), ('ECL_SIMPLE', 'ECL — simple model'), ('ECL_NONE', 'ECL — none'), ('IMPAIRMENT_ONLY', 'Impairment only'), ('FAIR_VALUE_REVIEW', 'Fair-value review'), ('CASE_BY_CASE', 'Case-by-case')], max_length=24)),
                ('esg_or_restriction_flag', models.BooleanField(default=False)),
                ('restriction_type_code', models.CharField(blank=True, max_length=40)),
                ('inception_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('settlement_cycle', models.CharField(blank=True, choices=[('T_PLUS_0', 'T+0 / same day'), ('T_PLUS_1', 'T+1'), ('T_PLUS_2', 'T+2'), ('MONTHLY', 'Monthly'), ('NA', 'Not applicable')], max_length=12)),
                ('day_count_convention', models.CharField(blank=True, max_length=16)),
                ('performance_group', models.CharField(blank=True, max_length=40)),
                ('report_category_code', models.CharField(blank=True, max_length=40)),
                ('default_principal_account_code', models.CharField(blank=True, max_length=20)),
                ('default_income_account_code', models.CharField(blank=True, max_length=20)),
                ('default_expense_account_code', models.CharField(blank=True, max_length=20)),
                ('default_realized_gl_account_code', models.CharField(blank=True, max_length=20)),
                ('default_unrealized_gl_account_code', models.CharField(blank=True, max_length=20)),
                ('default_fx_gl_account_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MATURED', 'Matured'), ('REDEEMED', 'Redeemed'), ('DELISTED', 'Delisted'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=16)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('workbook_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments_default_expense', to='beakon_core.account')),
                ('default_fx_gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments_default_fx_gl', to='beakon_core.account')),
                ('default_income_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments_default_income', to='beakon_core.account')),
                ('default_principal_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments_default_principal', to='beakon_core.account')),
                ('default_realized_gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments_default_realized_gl', to='beakon_core.account')),
                ('default_unrealized_gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments_default_unrealized_gl', to='beakon_core.account')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='beakon_core.loan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_instruments', to='organizations.organization')),
            ],
            options={
                'db_table': 'beakon_instrument',
                'ordering': ['instrument_id'],
                'indexes': [models.Index(fields=['organization', 'instrument_type'], name='beakon_inst_organiz_231798_idx'), models.Index(fields=['organization', 'quoted_unquoted_flag'], name='beakon_inst_organiz_1b18ac_idx'), models.Index(fields=['organization', 'status'], name='beakon_inst_organiz_0b97a3_idx'), models.Index(fields=['organization', 'portfolio_default'], name='beakon_inst_organiz_58198c_idx'), models.Index(fields=['organization', 'custodian_default'], name='beakon_inst_organiz_e13d38_idx'), models.Index(fields=['organization', 'asset_class_code'], name='beakon_inst_organiz_53d54b_idx'), models.Index(fields=['organization', 'loan'], name='beakon_inst_organiz_c9d607_idx')],
                'unique_together': {('organization', 'instrument_id')},
            },
        ),
    ]
