# Generated by Django 6.0.4 on 2026-05-01 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0018_instrument'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.CharField(help_text='Stable workbook identifier, e.g. PORT_MAIN.', max_length=80)),
                ('portfolio_name', models.CharField(blank=True, max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=80)),
                ('portfolio_type', models.CharField(blank=True, choices=[('PERSONAL', 'Personal'), ('COMPANY', 'Company'), ('FAMILY', 'Family'), ('FOUNDATION', 'Foundation'), ('INVESTMENT', 'Investment'), ('PARTNERSHIP', 'Partnership'), ('TRUST', 'Trust')], max_length=20)),
                ('portfolio_subtype', models.CharField(blank=True, max_length=40)),
                ('owner_type', models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('FOUNDATION', 'Foundation'), ('PARTNERSHIP', 'Partnership'), ('TRUST', 'Trust')], max_length=20)),
                ('owner_id', models.CharField(blank=True, help_text='Owner code (RP_*, CO_*, …); FK to RelatedParty/Entity once those masters exist.', max_length=80)),
                ('primary_related_party_id', models.CharField(blank=True, help_text='RP_* code; FK to RelatedParty later.', max_length=80)),
                ('linked_custodian_id', models.CharField(blank=True, help_text='CUST_* code; FK to Custodian later.', max_length=80)),
                ('base_currency', models.CharField(blank=True, max_length=3)),
                ('reporting_currency', models.CharField(blank=True, max_length=3)),
                ('country_code', models.CharField(blank=True, max_length=4)),
                ('jurisdiction_code', models.CharField(blank=True, max_length=20)),
                ('strategy_code', models.CharField(blank=True, max_length=40)),
                ('asset_allocation_profile', models.CharField(blank=True, max_length=40)),
                ('discretionary_flag', models.BooleanField(default=False)),
                ('consolidation_flag', models.BooleanField(default=True)),
                ('net_worth_inclusion_flag', models.BooleanField(default=True)),
                ('performance_report_flag', models.BooleanField(default=True)),
                ('posting_allowed_flag', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=12)),
                ('active_flag', models.BooleanField(default=True)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('parent_portfolio_workbook_id', models.CharField(blank=True, help_text='Workbook Parent_Portfolio_ID. Resolved to the parent FK at import time.', max_length=80)),
                ('reporting_group', models.CharField(blank=True, max_length=40)),
                ('approval_required_flag', models.BooleanField(default=True)),
                ('source_document_required_flag', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('workbook_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_portfolios', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='beakon_core.portfolio')),
            ],
            options={
                'db_table': 'beakon_portfolio',
                'ordering': ['portfolio_id'],
                'indexes': [models.Index(fields=['organization', 'portfolio_type'], name='beakon_port_organiz_55a598_idx'), models.Index(fields=['organization', 'status'], name='beakon_port_organiz_0f6085_idx'), models.Index(fields=['organization', 'linked_custodian_id'], name='beakon_port_organiz_fea549_idx'), models.Index(fields=['organization', 'owner_id'], name='beakon_port_organiz_85b702_idx'), models.Index(fields=['organization', 'parent'], name='beakon_port_organiz_2cd070_idx')],
                'unique_together': {('organization', 'portfolio_id')},
            },
        ),
    ]
