# Generated by Django 6.0.4 on 2026-05-01 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0019_portfolio'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custodian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custodian_id', models.CharField(help_text='Stable workbook identifier, e.g. CUST_UBS_ZRH.', max_length=80)),
                ('custodian_name', models.CharField(blank=True, max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=80)),
                ('custodian_type', models.CharField(blank=True, choices=[('PRIVATE_BANK', 'Private bank'), ('GLOBAL_CUSTODIAN', 'Global custodian'), ('BROKER_CUSTODIAN', 'Broker custodian'), ('CUSTODY_AGENT', 'Custody agent'), ('NOMINEE_PLATFORM', 'Nominee platform'), ('DIGITAL_CUSTODIAN', 'Digital-asset custodian'), ('TRANSFER_AGENT', 'Transfer agent'), ('CUSTODIAN', 'Custodian (generic)')], max_length=24)),
                ('custodian_subtype', models.CharField(blank=True, max_length=120)),
                ('linked_counterparty_id', models.CharField(blank=True, help_text='CP_* code; FK to Counterparty later.', max_length=80)),
                ('legal_entity_name', models.CharField(blank=True, max_length=255)),
                ('booking_center', models.CharField(blank=True, max_length=80)),
                ('country_code', models.CharField(blank=True, max_length=4)),
                ('jurisdiction_code', models.CharField(blank=True, max_length=20)),
                ('base_currency', models.CharField(blank=True, max_length=3)),
                ('reporting_currency', models.CharField(blank=True, max_length=3)),
                ('relationship_start_date', models.DateField(blank=True, null=True)),
                ('relationship_end_date', models.DateField(blank=True, null=True)),
                ('supports_listed_securities_flag', models.BooleanField(default=False)),
                ('supports_private_assets_flag', models.BooleanField(default=False)),
                ('supports_funds_flag', models.BooleanField(default=False)),
                ('supports_derivatives_flag', models.BooleanField(default=False)),
                ('supports_digital_assets_flag', models.BooleanField(default=False)),
                ('supports_cash_sweep_flag', models.BooleanField(default=False)),
                ('nominee_holding_flag', models.BooleanField(default=False)),
                ('segregated_account_flag', models.BooleanField(default=False)),
                ('default_portfolio_code', models.CharField(blank=True, help_text='PORT_* code from workbook. Resolved to default_portfolio at import.', max_length=80)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=12)),
                ('active_flag', models.BooleanField(default=True)),
                ('posting_allowed_flag', models.BooleanField(default=True)),
                ('approval_required_flag', models.BooleanField(default=True)),
                ('source_document_required_flag', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('workbook_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodians_defaulting_to', to='beakon_core.portfolio')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_custodians', to='organizations.organization')),
            ],
            options={
                'db_table': 'beakon_custodian',
                'ordering': ['custodian_id'],
                'indexes': [models.Index(fields=['organization', 'custodian_type'], name='beakon_cust_organiz_53ea6d_idx'), models.Index(fields=['organization', 'status'], name='beakon_cust_organiz_5c9289_idx'), models.Index(fields=['organization', 'country_code'], name='beakon_cust_organiz_d0a30b_idx'), models.Index(fields=['organization', 'linked_counterparty_id'], name='beakon_cust_organiz_1326ba_idx'), models.Index(fields=['organization', 'default_portfolio'], name='beakon_cust_organiz_9a828f_idx')],
                'unique_together': {('organization', 'custodian_id')},
            },
        ),
    ]
