# Generated by Django 6.0.4 on 2026-05-01 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0020_custodian'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_party_id', models.CharField(help_text='Stable workbook identifier, e.g. RP_CLIENT_001 / RP_HOLDCO_001 / FAM_CHILD1.', max_length=80)),
                ('related_party_name', models.CharField(blank=True, max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=80)),
                ('related_party_type', models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('TRUST', 'Trust'), ('FOUNDATION', 'Foundation'), ('PARTNERSHIP', 'Partnership')], max_length=20)),
                ('related_party_subtype', models.CharField(blank=True, max_length=120)),
                ('party_form', models.CharField(blank=True, choices=[('PERSON', 'Person'), ('ENTITY', 'Entity')], max_length=10)),
                ('relationship_to_client', models.CharField(blank=True, max_length=40)),
                ('ownership_percent', models.DecimalField(blank=True, decimal_places=4, help_text='Percent ownership of/by this party (0–100).', max_digits=8, null=True)),
                ('control_flag', models.BooleanField(default=False)),
                ('beneficiary_flag', models.BooleanField(default=False)),
                ('settlor_flag', models.BooleanField(default=False)),
                ('protector_flag', models.BooleanField(default=False)),
                ('director_flag', models.BooleanField(default=False)),
                ('signer_flag', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=12)),
                ('active_flag', models.BooleanField(default=True)),
                ('country_code', models.CharField(blank=True, max_length=4)),
                ('jurisdiction_code', models.CharField(blank=True, max_length=20)),
                ('base_currency', models.CharField(blank=True, max_length=3)),
                ('reporting_currency', models.CharField(blank=True, max_length=3)),
                ('tax_residence_country', models.CharField(blank=True, max_length=4)),
                ('related_party_since', models.DateField(blank=True, null=True)),
                ('related_party_until', models.DateField(blank=True, null=True)),
                ('loan_eligible_flag', models.BooleanField(default=False)),
                ('distribution_eligible_flag', models.BooleanField(default=False)),
                ('capital_contribution_eligible_flag', models.BooleanField(default=False)),
                ('expense_allocation_eligible_flag', models.BooleanField(default=False)),
                ('family_expense_eligible_flag', models.BooleanField(default=False)),
                ('net_worth_inclusion_flag', models.BooleanField(default=False)),
                ('default_portfolio_code', models.CharField(blank=True, help_text='PORT_* code from workbook. Resolved to default_portfolio at import.', max_length=80)),
                ('default_property_code', models.CharField(blank=True, help_text='PROP_* code; FK to Property once that master exists.', max_length=80)),
                ('default_bank_reference', models.CharField(blank=True, help_text='BANKREF_* / BA_* code; FK to BankAccount once that master is rebuilt.', max_length=80)),
                ('source_document_required_flag', models.BooleanField(default=True)),
                ('approval_required_flag', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('workbook_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_parties_defaulting_to', to='beakon_core.portfolio')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_related_parties', to='organizations.organization')),
            ],
            options={
                'db_table': 'beakon_related_party',
                'ordering': ['related_party_id'],
                'indexes': [models.Index(fields=['organization', 'related_party_type'], name='beakon_rela_organiz_7f3973_idx'), models.Index(fields=['organization', 'status'], name='beakon_rela_organiz_f2f0e2_idx'), models.Index(fields=['organization', 'country_code'], name='beakon_rela_organiz_c6952f_idx'), models.Index(fields=['organization', 'default_portfolio'], name='beakon_rela_organiz_908d0b_idx'), models.Index(fields=['organization', 'control_flag'], name='beakon_rela_organiz_727a87_idx'), models.Index(fields=['organization', 'beneficiary_flag'], name='beakon_rela_organiz_7b93fb_idx')],
                'unique_together': {('organization', 'related_party_id')},
            },
        ),
    ]
