# Generated by Django 6.0.4 on 2026-05-02 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0022_counterparty_bankaccount_property_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties_defaulting_to', to='beakon_core.bankaccount'),
        ),
        migrations.AddField(
            model_name='custodian',
            name='linked_counterparty_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodians_linked', to='beakon_core.counterparty'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='custodian_default_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments_default_to', to='beakon_core.custodian'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='issuer_counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments_issued', to='beakon_core.counterparty'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='issuer_related_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments_issued', to='beakon_core.relatedparty'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='portfolio_default_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments_default_to', to='beakon_core.portfolio'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='dimension_commitment_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='journalline',
            name='dimension_counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='beakon_core.counterparty'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='dimension_family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines_as_family_member', to='beakon_core.relatedparty'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='dimension_jurisdiction_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='journalline',
            name='dimension_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='beakon_core.loan'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='dimension_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='beakon_core.policy'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='dimension_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='beakon_core.property'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='dimension_related_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines_as_party', to='beakon_core.relatedparty'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='dimension_report_category_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='journalline',
            name='dimension_restriction_type_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='journalline',
            name='dimension_tax_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='beakon_core.taxlot'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='dimension_transfer_type_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='journalline',
            name='dimension_wallet_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='loan',
            name='borrower_or_lender_counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_as_borrower_or_lender', to='beakon_core.counterparty'),
        ),
        migrations.AddField(
            model_name='loan',
            name='borrower_or_lender_related_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_as_borrower_or_lender', to='beakon_core.relatedparty'),
        ),
        migrations.AddField(
            model_name='loan',
            name='reporting_portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_reporting', to='beakon_core.portfolio'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='linked_custodian_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios_linked', to='beakon_core.custodian'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='owner_related_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios_owned_as_owner', to='beakon_core.relatedparty'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='primary_related_party_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios_primary', to='beakon_core.relatedparty'),
        ),
        migrations.AddField(
            model_name='relatedparty',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_parties_defaulting_to', to='beakon_core.bankaccount'),
        ),
        migrations.AddField(
            model_name='relatedparty',
            name='default_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_parties_defaulting_to', to='beakon_core.property'),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_lots', to='beakon_core.custodian'),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_lots', to='beakon_core.instrument'),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_lots', to='beakon_core.portfolio'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='default_bank_reference',
            field=models.CharField(blank=True, help_text='BANKREF_* / BA_* code. Mirrored to ``default_bank_account`` FK at import.', max_length=80),
        ),
        migrations.AlterField(
            model_name='custodian',
            name='linked_counterparty_id',
            field=models.CharField(blank=True, help_text='CP_* code. Mirrored to ``linked_counterparty_obj`` FK at import.', max_length=80),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='custodian_default',
            field=models.CharField(blank=True, help_text='CUST_* code. Mirrored to ``custodian_default_obj`` FK at import.', max_length=40),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='issuer_or_counterparty_code',
            field=models.CharField(blank=True, help_text='Issuer code (CP_*) or related-party (RP_*). The import command sets the matching FK below based on prefix.', max_length=80),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='portfolio_default',
            field=models.CharField(blank=True, help_text='PORT_* code. Mirrored to ``portfolio_default_obj`` FK at import.', max_length=40),
        ),
        migrations.AlterField(
            model_name='loan',
            name='borrower_or_lender_code',
            field=models.CharField(blank=True, help_text='Counterparty (CP_*) or RelatedParty (RP_*) code. The import command sets the matching FK below based on prefix.', max_length=80),
        ),
        migrations.AlterField(
            model_name='loan',
            name='reporting_portfolio_code',
            field=models.CharField(blank=True, help_text='Workbook Portfolio code. Mirrored to ``reporting_portfolio`` FK.', max_length=80),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='linked_custodian_id',
            field=models.CharField(blank=True, help_text='CUST_* code. Mirrored to ``linked_custodian_obj`` FK at import.', max_length=80),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='owner_id',
            field=models.CharField(blank=True, help_text='Owner code (RP_* primarily). Mirrored to ``owner_related_party`` FK at import.', max_length=80),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='primary_related_party_id',
            field=models.CharField(blank=True, help_text='RP_* code. Mirrored to ``primary_related_party_obj`` FK at import.', max_length=80),
        ),
        migrations.AlterField(
            model_name='relatedparty',
            name='default_bank_reference',
            field=models.CharField(blank=True, help_text='BANKREF_* / BA_* code. Mirrored to ``default_bank_account`` FK at import.', max_length=80),
        ),
        migrations.AlterField(
            model_name='relatedparty',
            name='default_property_code',
            field=models.CharField(blank=True, help_text='PROP_* code. Mirrored to ``default_property`` FK at import.', max_length=80),
        ),
        migrations.AlterField(
            model_name='taxlot',
            name='custodian_code',
            field=models.CharField(blank=True, help_text='Workbook Custodian_ID. Mirrored to ``custodian`` FK at import.', max_length=80),
        ),
        migrations.AlterField(
            model_name='taxlot',
            name='instrument_code',
            field=models.CharField(blank=True, help_text='Workbook Instrument_ID. Mirrored to ``instrument`` FK at import.', max_length=80),
        ),
        migrations.AlterField(
            model_name='taxlot',
            name='portfolio_code',
            field=models.CharField(blank=True, help_text='Workbook Portfolio_ID. Mirrored to ``portfolio`` FK at import.', max_length=80),
        ),
    ]
