# Generated by Django 6.0.4 on 2026-05-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0023_counterparty_default_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='allow_foreign_currency_posting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='client_view_category',
            field=models.CharField(blank=True, help_text='Workbook Client_View_Category — presentation grouping for client-facing statements.', max_length=60),
        ),
        migrations.AddField(
            model_name='account',
            name='economic_nature',
            field=models.CharField(blank=True, help_text='Workbook Economic_Nature, e.g. BALANCE_SHEET, ACCRUAL, PORTFOLIO_ASSET, RELATED_PARTY_BALANCE, SETTLEMENT, IMPAIRMENT, CAPITAL_MOVEMENT, CLEARING, TAX.', max_length=40),
        ),
        migrations.AddField(
            model_name='account',
            name='fx_gain_loss_bucket',
            field=models.CharField(blank=True, help_text='Workbook FX_Gain_Loss_Bucket, e.g. UNREALIZED_FX / COMBINED_REALIZED_UNREALIZED / FAIR_VALUE_FX / NA.', max_length=40),
        ),
        migrations.AddField(
            model_name='account',
            name='fx_remeasure_flag',
            field=models.CharField(blank=True, help_text='Workbook FX_Remeasure_Flag — Yes / No / BY_VALUATION_METHOD.', max_length=24),
        ),
        migrations.AddField(
            model_name='account',
            name='historical_vs_closing_rate_method',
            field=models.CharField(blank=True, help_text='Workbook Historical_vs_Closing_Rate_Method, e.g. CLOSING / AVERAGE / HISTORICAL / FAIR_VALUE / NA.', max_length=24),
        ),
        migrations.AddField(
            model_name='account',
            name='subledger_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='subledger_type',
            field=models.CharField(blank=True, help_text='Workbook Subledger_Type, e.g. BANK / INVESTMENT / RELATED_PARTY / COUNTERPARTY / PROPERTY / FIXED_ASSET / NONE.', max_length=24),
        ),
        migrations.AddField(
            model_name='account',
            name='valuation_basis',
            field=models.CharField(blank=True, help_text='Workbook Valuation_Basis, e.g. FVPL / FAIR_VALUE / AMORTIZED_COST / COST / HISTORICAL / NA.', max_length=24),
        ),
        migrations.AlterField(
            model_name='account',
            name='workbook_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional workbook columns preserved for round-trip safety.'),
        ),
    ]
