# Generated by Django 6.0.4 on 2026-05-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0024_account_allow_foreign_currency_posting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coadefinition',
            name='description',
            field=models.TextField(blank=True, help_text='Workbook 01_CoA_Definition.Description — narrative scope of the CoA. Distinct from `notes` (which holds free-text editorial comments).'),
        ),
        migrations.AddField(
            model_name='coadefinition',
            name='dimensions_enabled',
            field=models.BooleanField(default=False, help_text='Workbook 01_CoA_Definition.Dimensions_Enabled — gates whether the dimension layer (DimensionType / DimensionValue / validation rules) is enforced on this CoA. Flat-only CoAs leave this off.'),
        ),
        migrations.AddField(
            model_name='coadefinition',
            name='governed_instruments_enabled',
            field=models.BooleanField(default=False, help_text='Workbook 01_CoA_Definition.Governed_Instruments_Enabled — gates whether Loan / Instrument / Commitment / Policy masters are usable on this CoA.'),
        ),
        migrations.AddField(
            model_name='coadefinition',
            name='universal_mapping_required',
            field=models.BooleanField(default=False, help_text='Workbook 01_CoA_Definition.Universal_Mapping_Required — when true, every Account must carry a 03_CoA_Mapping row to the universal CoA.'),
        ),
    ]
