# Generated by Django 6.0.4 on 2026-05-02 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0025_coadefinition_description_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pension_id', models.CharField(help_text='Stable identifier — e.g. PEN_LPP_001, PEN_PILLAR3A_001.', max_length=80)),
                ('pension_name', models.CharField(blank=True, max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=80)),
                ('pension_type', models.CharField(blank=True, help_text='LPP_2ND_PILLAR / PILLAR_3A / PILLAR_3B / FOREIGN_PENSION / EMPLOYER_DC / EMPLOYER_DB / OTHER.', max_length=40)),
                ('pension_subtype', models.CharField(blank=True, max_length=40)),
                ('holder_related_party_id_code', models.CharField(blank=True, max_length=80)),
                ('provider_counterparty_id_code', models.CharField(blank=True, max_length=80)),
                ('employer_counterparty_id_code', models.CharField(blank=True, max_length=80)),
                ('plan_number_masked', models.CharField(blank=True, max_length=80)),
                ('contribution_basis', models.CharField(blank=True, help_text='DEFINED_CONTRIBUTION / DEFINED_BENEFIT / HYBRID.', max_length=40)),
                ('vesting_status', models.CharField(blank=True, help_text='VESTED / PARTIALLY_VESTED / UNVESTED.', max_length=40)),
                ('country_code', models.CharField(blank=True, max_length=4)),
                ('jurisdiction_code', models.CharField(blank=True, max_length=20)),
                ('pension_currency', models.CharField(blank=True, max_length=3)),
                ('reporting_currency', models.CharField(blank=True, max_length=3)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('earliest_withdrawal_date', models.DateField(blank=True, help_text='Earliest date holder may legally draw benefits — e.g. age 60 for Swiss Pillar 3A; varies by jurisdiction.', null=True)),
                ('expected_retirement_date', models.DateField(blank=True, null=True)),
                ('payout_start_date', models.DateField(blank=True, null=True)),
                ('closure_date', models.DateField(blank=True, null=True)),
                ('contributions_to_date', models.DecimalField(blank=True, decimal_places=4, help_text='Cumulative contributions (employee + employer) since inception, in pension_currency.', max_digits=24, null=True)),
                ('vested_balance', models.DecimalField(blank=True, decimal_places=4, help_text='Current vested cash value, in pension_currency.', max_digits=24, null=True)),
                ('projected_benefit', models.DecimalField(blank=True, decimal_places=4, help_text='Estimated benefit at retirement — DB plans or projected DC.', max_digits=24, null=True)),
                ('employer_contribution_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Percentage (0–100). NULL for non-employer plans.', max_digits=7, null=True)),
                ('employee_contribution_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('linked_portfolio_id_code', models.CharField(blank=True, max_length=80)),
                ('linked_bank_account_id_code', models.CharField(blank=True, max_length=80)),
                ('tax_privileged_flag', models.BooleanField(default=False, help_text='True for tax-advantaged plans (Pillar 3A, 401(k), IRA, etc.).')),
                ('employer_sponsored_flag', models.BooleanField(default=False)),
                ('net_worth_inclusion_flag', models.BooleanField(default=True, help_text='Include in client net-worth reporting. Some jurisdictions exclude unvested balances.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=12)),
                ('active_flag', models.BooleanField(default=True)),
                ('posting_allowed_flag', models.BooleanField(default=True)),
                ('approval_required_flag', models.BooleanField(default=True)),
                ('source_document_required_flag', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('workbook_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_counterparty', models.ForeignKey(blank=True, help_text='Sponsoring employer for occupational schemes (LPP / DC / DB).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pensions_employer', to='beakon_core.counterparty')),
                ('holder_related_party', models.ForeignKey(blank=True, help_text='The person whose retirement savings this represents.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pensions_held', to='beakon_core.relatedparty')),
                ('linked_bank_account', models.ForeignKey(blank=True, help_text='Bank account from which contributions are paid (for personal pillars).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pensions_funded', to='beakon_core.bankaccount')),
                ('linked_portfolio', models.ForeignKey(blank=True, help_text='Portfolio bucket where the pension is reported.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pensions', to='beakon_core.portfolio')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_pensions', to='organizations.organization')),
                ('provider_counterparty', models.ForeignKey(blank=True, help_text='The pension fund / insurer / institution administering the plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pensions_provided', to='beakon_core.counterparty')),
            ],
            options={
                'verbose_name_plural': 'pensions',
                'db_table': 'beakon_pension',
                'ordering': ['pension_id'],
            },
        ),
        migrations.AddField(
            model_name='journalline',
            name='dimension_pension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='beakon_core.pension'),
        ),
        migrations.AddIndex(
            model_name='pension',
            index=models.Index(fields=['organization', 'pension_type'], name='beakon_pens_organiz_6e0b03_idx'),
        ),
        migrations.AddIndex(
            model_name='pension',
            index=models.Index(fields=['organization', 'status'], name='beakon_pens_organiz_7fe803_idx'),
        ),
        migrations.AddIndex(
            model_name='pension',
            index=models.Index(fields=['organization', 'holder_related_party'], name='beakon_pens_organiz_ee4b21_idx'),
        ),
        migrations.AddIndex(
            model_name='pension',
            index=models.Index(fields=['organization', 'provider_counterparty'], name='beakon_pens_organiz_16e26d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pension',
            unique_together={('organization', 'pension_id')},
        ),
    ]
