# Generated by Django 6.0.4 on 2026-05-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0027_seed_pen_dimension_type'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_id', models.CharField(help_text='Stable identifier — e.g. COM_PE_001, COM_VC_002.', max_length=80)),
                ('commitment_name', models.CharField(blank=True, max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=80)),
                ('commitment_type', models.CharField(blank=True, help_text='LP_FUND / DIRECT_PRIVATE / CO_INVEST / REAL_ESTATE_FUND / OTHER.', max_length=40)),
                ('commitment_subtype', models.CharField(blank=True, max_length=40)),
                ('holder_related_party_id_code', models.CharField(blank=True, max_length=80)),
                ('general_partner_counterparty_id_code', models.CharField(blank=True, max_length=80)),
                ('vehicle_instrument_id_code', models.CharField(blank=True, max_length=80)),
                ('country_code', models.CharField(blank=True, max_length=4)),
                ('jurisdiction_code', models.CharField(blank=True, max_length=20)),
                ('commitment_currency', models.CharField(blank=True, max_length=3)),
                ('reporting_currency', models.CharField(blank=True, max_length=3)),
                ('vintage_year', models.IntegerField(blank=True, null=True)),
                ('inception_date', models.DateField(blank=True, null=True)),
                ('final_close_date', models.DateField(blank=True, null=True)),
                ('investment_period_end_date', models.DateField(blank=True, null=True)),
                ('expected_term_years', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('closure_date', models.DateField(blank=True, null=True)),
                ('total_commitment_amount', models.DecimalField(blank=True, decimal_places=4, help_text='Total committed capital (the headline subscription amount).', max_digits=24, null=True)),
                ('called_to_date', models.DecimalField(blank=True, decimal_places=4, help_text='Cumulative drawn capital from capital calls.', max_digits=24, null=True)),
                ('distributions_to_date', models.DecimalField(blank=True, decimal_places=4, help_text='Cumulative cash distributed back to the LP.', max_digits=24, null=True)),
                ('unfunded_balance', models.DecimalField(blank=True, decimal_places=4, help_text='Remaining uncalled commitment. Should equal total - called + recallable.', max_digits=24, null=True)),
                ('nav', models.DecimalField(blank=True, decimal_places=4, help_text='Latest reported net asset value of the LP interest.', max_digits=24, null=True)),
                ('nav_date', models.DateField(blank=True, null=True)),
                ('management_fee_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Annual management fee percentage (0–100).', max_digits=7, null=True)),
                ('carried_interest_rate', models.DecimalField(blank=True, decimal_places=4, help_text='GP carry percentage (0–100).', max_digits=7, null=True)),
                ('hurdle_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Preferred return percentage before carry kicks in.', max_digits=7, null=True)),
                ('linked_portfolio_id_code', models.CharField(blank=True, max_length=80)),
                ('funding_bank_account_id_code', models.CharField(blank=True, max_length=80)),
                ('recallable_distributions_flag', models.BooleanField(default=False, help_text='True if distributions can be recalled by the GP, increasing unfunded balance.')),
                ('net_worth_inclusion_flag', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FULLY_CALLED', 'Fully Called'), ('WOUND_DOWN', 'Wound Down'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=14)),
                ('active_flag', models.BooleanField(default=True)),
                ('posting_allowed_flag', models.BooleanField(default=True)),
                ('approval_required_flag', models.BooleanField(default=True)),
                ('source_document_required_flag', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('workbook_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funding_bank_account', models.ForeignKey(blank=True, help_text='Bank account from which capital calls are paid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments_funded', to='beakon_core.bankaccount')),
                ('general_partner_counterparty', models.ForeignKey(blank=True, help_text='GP / sponsor / fund manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments_as_gp', to='beakon_core.counterparty')),
                ('holder_related_party', models.ForeignKey(blank=True, help_text='Investor / LP — the party that has committed capital.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments_held', to='beakon_core.relatedparty')),
                ('linked_portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='beakon_core.portfolio')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_commitments', to='organizations.organization')),
                ('vehicle_instrument', models.ForeignKey(blank=True, help_text='The fund / vehicle this commitment subscribes into, if modelled as an Instrument.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='beakon_core.instrument')),
            ],
            options={
                'db_table': 'beakon_commitment',
                'ordering': ['commitment_id'],
            },
        ),
        migrations.AddField(
            model_name='journalline',
            name='dimension_commitment',
            field=models.ForeignKey(blank=True, help_text='FK promotion of dimension_commitment_code. Either being set satisfies the COM dimension requirement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='beakon_core.commitment'),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['organization', 'commitment_type'], name='beakon_comm_organiz_1640a9_idx'),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['organization', 'status'], name='beakon_comm_organiz_900ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['organization', 'holder_related_party'], name='beakon_comm_organiz_536834_idx'),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['organization', 'general_partner_counterparty'], name='beakon_comm_organiz_f08163_idx'),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['organization', 'vintage_year'], name='beakon_comm_organiz_fe189f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commitment',
            unique_together={('organization', 'commitment_id')},
        ),
    ]
