# Generated by Django 6.0.4 on 2026-05-02 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0028_commitment_journalline_dimension_commitment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='rebilled_invoice_line',
            field=models.ForeignKey(blank=True, help_text='Set when DisbursementService bills this rebillable cost to a client. NULL means the cost is still pending recovery. Prevents double-billing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebilled_journal_lines', to='beakon_core.invoiceline'),
        ),
    ]
