# Generated by Django 6.0.4 on 2026-05-02 21:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0029_journalline_rebilled_invoice_line'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billline',
            name='tax_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='VAT amount on this line. Auto-derivable from tax_code.rate × amount, but stored explicitly so manual overrides + rounding decisions stick.', max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tax_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='VAT amount on this line. Auto-derivable from tax_code.rate × amount, but stored explicitly so manual overrides + rounding decisions stick.', max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable identifier — e.g. CH-VAT-STD, CH-VAT-RED, CH-VAT-ZERO.', max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('country_code', models.CharField(blank=True, help_text='ISO country code, e.g. CH, DE, GB.', max_length=4)),
                ('tax_type', models.CharField(choices=[('STANDARD', 'Standard'), ('REDUCED', 'Reduced'), ('SPECIAL', 'Special'), ('ZERO', 'Zero-rated'), ('EXEMPT', 'Exempt'), ('REVERSE_CHARGE', 'Reverse charge')], default='STANDARD', max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Percentage rate. 8.1000 means 8.1%.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('is_reverse_charge', models.BooleanField(default=False, help_text='If true, posting books both DR Input VAT and CR Output VAT for the same amount (B2B cross-border services in EU/CH).')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('active_flag', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('workbook_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_account', models.ForeignKey(blank=True, help_text='GL account debited on purchases (typically vat_receivable). NULL = non-recoverable (e.g. exempt) — VAT cost gets baked into expense.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_codes_as_input', to='beakon_core.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_codes', to='organizations.organization')),
                ('output_account', models.ForeignKey(blank=True, help_text='GL account credited on sales (typically a vat_payable subtype). Can be NULL for purchase-only codes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_codes_as_output', to='beakon_core.account')),
            ],
            options={
                'db_table': 'beakon_tax_code',
                'ordering': ['country_code', 'code'],
            },
        ),
        migrations.AddField(
            model_name='billline',
            name='tax_code',
            field=models.ForeignKey(blank=True, help_text='VAT/tax code applied to this line. NULL = no tax on this line.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='beakon_core.taxcode'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tax_code',
            field=models.ForeignKey(blank=True, help_text='VAT/tax code applied to this line. NULL = no tax on this line.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='beakon_core.taxcode'),
        ),
        migrations.AddIndex(
            model_name='taxcode',
            index=models.Index(fields=['organization', 'active_flag'], name='beakon_tax__organiz_c79235_idx'),
        ),
        migrations.AddIndex(
            model_name='taxcode',
            index=models.Index(fields=['organization', 'country_code'], name='beakon_tax__organiz_cd72af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxcode',
            unique_together={('organization', 'code')},
        ),
    ]
