# Generated by Django 6.0.4 on 2026-05-02 21:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0030_billline_tax_amount_invoiceline_tax_amount_taxcode_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('bill', 'Bill'), ('bill_payment', 'Bill Payment'), ('invoice', 'Invoice'), ('invoice_payment', 'Invoice Payment'), ('bank_transaction', 'Bank Transaction'), ('intercompany', 'Intercompany'), ('opening_balance', 'Opening Balance'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal'), ('fx_revaluation', 'FX Revaluation'), ('period_close', 'Period Close'), ('recognition', 'Recognition / Accrual')], default='manual', max_length=50),
        ),
        migrations.CreateModel(
            name='RecognitionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable identifier — e.g. PREPAID-INS-2026, DEF-REV-Q3.', max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('PREPAID_EXPENSE', 'Prepaid expense (amortize over time)'), ('DEFERRED_REVENUE', 'Deferred revenue (release over time)'), ('ACCRUED_EXPENSE', 'Accrued expense (recognise before invoice)'), ('ACCRUED_REVENUE', 'Accrued revenue (recognise before invoice)')], max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('recognized_to_date', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=12)),
                ('method', models.CharField(choices=[('STRAIGHT_LINE_BY_PERIOD', 'Straight line — equal amount per period (rounding lands on last)'), ('STRAIGHT_LINE_BY_DAY', 'Straight line — pro-rata by day count')], default='STRAIGHT_LINE_BY_PERIOD', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=12)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_rules_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_rules_created', to=settings.AUTH_USER_MODEL)),
                ('deferral_account', models.ForeignKey(help_text='Balance-sheet account holding the unrecognised amount.', on_delete=django.db.models.deletion.PROTECT, related_name='recognition_rules_as_deferral', to='beakon_core.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recognition_rules', to='beakon_core.entity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_rules', to='organizations.organization')),
                ('recognition_account', models.ForeignKey(help_text="P&L account each period's recognised amount lands on.", on_delete=django.db.models.deletion.PROTECT, related_name='recognition_rules_as_recognition', to='beakon_core.account')),
                ('source_bill_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_rules', to='beakon_core.billline')),
                ('source_invoice_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_rules', to='beakon_core.invoiceline')),
                ('source_journal_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_rules', to='beakon_core.journalline')),
            ],
            options={
                'db_table': 'beakon_recognition_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='1-based ordinal — the Nth period in the schedule.')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_periods_posted', to=settings.AUTH_USER_MODEL)),
                ('posted_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_schedule_periods', to='beakon_core.journalentry')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_periods', to='beakon_core.recognitionrule')),
            ],
            options={
                'db_table': 'beakon_recognition_schedule',
                'ordering': ['rule', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='recognitionrule',
            index=models.Index(fields=['organization', 'status'], name='beakon_reco_organiz_eeb409_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionrule',
            index=models.Index(fields=['entity', 'status'], name='beakon_reco_entity__d5ab6d_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionrule',
            index=models.Index(fields=['rule_type', 'status'], name='beakon_reco_rule_ty_d5853a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recognitionrule',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='recognitionschedule',
            index=models.Index(fields=['rule', 'posted_journal_entry'], name='beakon_reco_rule_id_a31c36_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionschedule',
            index=models.Index(fields=['period_end'], name='beakon_reco_period__56d432_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recognitionschedule',
            unique_together={('rule', 'sequence')},
        ),
    ]
