# Generated by Django 6.0.4 on 2026-05-03 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0031_alter_journalentry_source_type_recognitionrule_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable identifier — e.g. ENGINE_FLOW, BILL_LIFECYCLE.', max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('mermaid_src', models.TextField(help_text='Mermaid source — see https://mermaid.js.org/syntax/flowchart.html')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_diagrams', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_diagrams_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'beakon_workflow_diagram',
                'ordering': ['code'],
                'unique_together': {('organization', 'code')},
            },
        ),
    ]
