# Generated by Django 6.0.4 on 2026-05-05 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0033_seed_engine_workflow_diagram'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='four_eyes_posting_required',
            field=models.BooleanField(default=False, help_text='When true, posting an approved JE requires a different user than the approver (true 4-eyes per architecture PDF §9). Default off — approve+post by same user is allowed.'),
        ),
        migrations.CreateModel(
            name='PostingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('supplier_invoice', 'Supplier invoice'), ('customer_invoice', 'Customer invoice'), ('supplier_payment', 'Supplier payment'), ('customer_receipt', 'Customer receipt'), ('bank_charge', 'Bank charge')], help_text='Which transaction type this rule covers.', max_length=40)),
                ('name', models.CharField(help_text="Human-readable description, e.g. 'Supplier invoice (AP accrual)'.", max_length=120)),
                ('debit_role', models.CharField(choices=[('accounts_payable', 'Accounts Payable (subtype-resolved)'), ('accounts_receivable', 'Accounts Receivable (subtype-resolved)'), ('bank', 'Bank account (caller-provided)'), ('expense', 'Expense account (caller-provided per line)'), ('revenue', 'Revenue account (caller-provided per line)'), ('bank_charge_expense', 'Bank-charge expense (auto or caller-provided)')], help_text='Role of the account on the debit side.', max_length=40)),
                ('credit_role', models.CharField(choices=[('accounts_payable', 'Accounts Payable (subtype-resolved)'), ('accounts_receivable', 'Accounts Receivable (subtype-resolved)'), ('bank', 'Bank account (caller-provided)'), ('expense', 'Expense account (caller-provided per line)'), ('revenue', 'Revenue account (caller-provided per line)'), ('bank_charge_expense', 'Bank-charge expense (auto or caller-provided)')], help_text='Role of the account on the credit side.', max_length=40)),
                ('description', models.TextField(blank=True, help_text='Optional teaching note shown next to AI proposals.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='Seeded by Beakon — block deletion in admin.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_posting_rules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_rules', to='organizations.organization')),
            ],
            options={
                'db_table': 'beakon_posting_rule',
                'ordering': ['transaction_type'],
                'unique_together': {('organization', 'transaction_type')},
            },
        ),
    ]
