# Generated by Django 6.0.4 on 2026-05-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0037_seed_tier1_posting_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingrule',
            name='credit_role',
            field=models.CharField(choices=[('accounts_payable', 'Accounts Payable (subtype-resolved)'), ('accounts_receivable', 'Accounts Receivable (subtype-resolved)'), ('bank', 'Bank account (caller-provided)'), ('expense', 'Expense account (caller-provided per line)'), ('revenue', 'Revenue account (caller-provided per line)'), ('bank_charge_expense', 'Bank-charge expense (auto or caller-provided)'), ('interest_income', 'Interest income (auto-resolve / caller-provided)'), ('capital', 'Capital — equity (subtype-resolved)'), ('vat_payable', 'VAT Payable (subtype-resolved)'), ('bank_target', 'Target bank account (caller-provided)'), ('bank_source', 'Source bank account (caller-provided)'), ('loan_payable', 'Loan Payable (subtype-resolved)'), ('loan_receivable', 'Loan Receivable (subtype-resolved)'), ('interest_expense', 'Interest expense (auto-resolve / caller-provided)'), ('investment', 'Investment (caller-provided)'), ('investment_gain', 'Investment gain — revenue (caller-provided)'), ('rental_income', 'Rental income (caller-provided)'), ('property_expense', 'Property expense (caller-provided)'), ('insurance_expense', 'Insurance expense (caller-provided)'), ('insurance_recovery', 'Insurance recovery — revenue (caller-provided)')], help_text='Role of the account on the credit side.', max_length=40),
        ),
        migrations.AlterField(
            model_name='postingrule',
            name='debit_role',
            field=models.CharField(choices=[('accounts_payable', 'Accounts Payable (subtype-resolved)'), ('accounts_receivable', 'Accounts Receivable (subtype-resolved)'), ('bank', 'Bank account (caller-provided)'), ('expense', 'Expense account (caller-provided per line)'), ('revenue', 'Revenue account (caller-provided per line)'), ('bank_charge_expense', 'Bank-charge expense (auto or caller-provided)'), ('interest_income', 'Interest income (auto-resolve / caller-provided)'), ('capital', 'Capital — equity (subtype-resolved)'), ('vat_payable', 'VAT Payable (subtype-resolved)'), ('bank_target', 'Target bank account (caller-provided)'), ('bank_source', 'Source bank account (caller-provided)'), ('loan_payable', 'Loan Payable (subtype-resolved)'), ('loan_receivable', 'Loan Receivable (subtype-resolved)'), ('interest_expense', 'Interest expense (auto-resolve / caller-provided)'), ('investment', 'Investment (caller-provided)'), ('investment_gain', 'Investment gain — revenue (caller-provided)'), ('rental_income', 'Rental income (caller-provided)'), ('property_expense', 'Property expense (caller-provided)'), ('insurance_expense', 'Insurance expense (caller-provided)'), ('insurance_recovery', 'Insurance recovery — revenue (caller-provided)')], help_text='Role of the account on the debit side.', max_length=40),
        ),
        migrations.AlterField(
            model_name='postingrule',
            name='transaction_type',
            field=models.CharField(choices=[('supplier_invoice', 'Supplier invoice'), ('customer_invoice', 'Customer invoice'), ('supplier_payment', 'Supplier payment'), ('customer_receipt', 'Customer receipt'), ('bank_charge', 'Bank charge'), ('bank_transfer', 'Bank transfer'), ('bank_interest', 'Bank interest received'), ('owner_contribution', 'Owner capital contribution'), ('vendor_credit_note', 'Vendor credit note'), ('customer_credit_note', 'Customer credit note'), ('vat_remittance', 'VAT remittance'), ('loan_drawdown', 'Loan drawdown'), ('loan_repayment', 'Loan repayment'), ('loan_interest_accrual', 'Loan interest accrual'), ('capital_call', 'Capital call (PE commitment drawdown)'), ('distribution', 'Distribution received (PE)'), ('rental_income', 'Rental income'), ('property_expense', 'Property expense'), ('insurance_premium', 'Insurance premium paid'), ('insurance_claim', 'Insurance claim received')], help_text='Which transaction type this rule covers.', max_length=40),
        ),
    ]
