# Generated by Django 6.0.4 on 2026-05-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0039_seed_tier2_posting_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='explanation',
            field=models.TextField(blank=True, help_text='Long-form reasoning: WHY this entry exists, WHY each side was debited or credited, and any judgement an auditor would want to see. Distinct from `memo` (which is a one-line subject).'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='memo',
            field=models.TextField(blank=True, help_text='One-line subject — auto-set by AI/OCR for bills + invoices.'),
        ),
    ]
