# Generated by Django 6.0.4 on 2026-05-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0040_journalentry_explanation_alter_journalentry_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='explanation',
            field=models.TextField(blank=True, help_text='Long-form rationale: WHY this bill exists and WHY each side of the resulting JE is debited or credited. Propagates to JournalEntry.explanation when the accrual JE posts.'),
        ),
    ]
