# Generated by Django 6.0.4 on 2026-05-08 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0042_invoice_explanation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sourcedocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='beakon_core.bill'),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='beakon_core.invoice'),
        ),
        migrations.AlterField(
            model_name='sourcedocument',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='beakon_core.journalentry'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['bill', 'is_deleted'], name='beakon_sour_bill_id_28f87c_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['invoice', 'is_deleted'], name='beakon_sour_invoice_a0ed84_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('journal_entry__isnull', False)), fields=('journal_entry', 'content_hash'), name='sourcedoc_unique_je_hash'),
        ),
        migrations.AddConstraint(
            model_name='sourcedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('bill__isnull', False)), fields=('bill', 'content_hash'), name='sourcedoc_unique_bill_hash'),
        ),
        migrations.AddConstraint(
            model_name='sourcedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice__isnull', False)), fields=('invoice', 'content_hash'), name='sourcedoc_unique_invoice_hash'),
        ),
    ]
