# Generated by Django 6.0.4 on 2026-05-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_banking', '0003_alter_feedimport_source_avaloqfeeddrop_and_more'),
        ('beakon_core', '0043_alter_sourcedocument_unique_together_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_order_id', models.CharField(max_length=80)),
                ('order_date', models.DateField()),
                ('isin', models.CharField(max_length=24)),
                ('instrument_name', models.CharField(blank=True, max_length=255)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=6, help_text='Null for market orders.', max_digits=20, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('order_status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL', 'Partially filled'), ('CANCELLED', 'Cancelled'), ('FILLED', 'Filled')], default='OPEN', max_length=12)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_orders', to='beakon_banking.avaloqfeeddrop')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_open_orders', to='organizations.organization')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='open_orders', to='beakon_core.portfolio')),
            ],
            options={
                'db_table': 'beakon_open_order',
                'ordering': ['-order_date', '-id'],
                'indexes': [models.Index(fields=['organization', 'portfolio', 'order_status'], name='beakon_open_organiz_f401cb_idx'), models.Index(fields=['drop'], name='beakon_open_drop_id_77525e_idx')],
                'unique_together': {('organization', 'external_order_id')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('period', models.CharField(choices=[('DTD', 'Day-to-date'), ('MTD', 'Month-to-date'), ('YTD', 'Year-to-date'), ('ITD', 'Inception-to-date')], max_length=4)),
                ('return_pct', models.DecimalField(decimal_places=4, help_text='Period return in percent, e.g. 1.2500 = +1.25%.', max_digits=10)),
                ('return_amount', models.DecimalField(blank=True, decimal_places=4, help_text="Absolute P&L in the portfolio's reporting currency.", max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_snapshots', to='beakon_banking.avaloqfeeddrop')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_performance_snapshots', to='organizations.organization')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_snapshots', to='beakon_core.portfolio')),
            ],
            options={
                'db_table': 'beakon_performance_snapshot',
                'ordering': ['-as_of', 'portfolio_id', 'period'],
                'indexes': [models.Index(fields=['organization', 'portfolio', 'as_of'], name='beakon_perf_organiz_7cdd1e_idx'), models.Index(fields=['drop'], name='beakon_perf_drop_id_a51f57_idx')],
                'unique_together': {('organization', 'portfolio', 'as_of', 'period')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_trade_id', models.CharField(help_text="Bank's stable trade reference. Idempotency key.", max_length=80)),
                ('trade_date', models.DateField()),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('isin', models.CharField(max_length=24)),
                ('instrument_name', models.CharField(blank=True, max_length=255)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('gross_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('fees', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('raw_row', models.JSONField(blank=True, default=dict, help_text='Verbatim CSV row for audit / re-parse.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='beakon_core.custodian')),
                ('drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_trades', to='beakon_banking.avaloqfeeddrop')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_portfolio_trades', to='organizations.organization')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='beakon_core.portfolio')),
            ],
            options={
                'db_table': 'beakon_portfolio_trade',
                'ordering': ['-trade_date', '-id'],
                'indexes': [models.Index(fields=['organization', 'portfolio', 'trade_date'], name='beakon_port_organiz_b9e2cb_idx'), models.Index(fields=['organization', 'isin'], name='beakon_port_organiz_a3489d_idx'), models.Index(fields=['drop'], name='beakon_port_drop_id_34403f_idx')],
                'unique_together': {('organization', 'external_trade_id')},
            },
        ),
        migrations.CreateModel(
            name='PositionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('isin', models.CharField(max_length=24)),
                ('instrument_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('market_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('average_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_snapshots', to='beakon_banking.avaloqfeeddrop')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakon_position_snapshots', to='organizations.organization')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_snapshots', to='beakon_core.portfolio')),
            ],
            options={
                'db_table': 'beakon_position_snapshot',
                'ordering': ['-as_of', 'isin'],
                'indexes': [models.Index(fields=['organization', 'portfolio', 'as_of'], name='beakon_posi_organiz_223a90_idx'), models.Index(fields=['organization', 'isin', 'as_of'], name='beakon_posi_organiz_7fe96d_idx'), models.Index(fields=['drop'], name='beakon_posi_drop_id_39b041_idx')],
                'unique_together': {('organization', 'portfolio', 'as_of', 'isin')},
            },
        ),
    ]
