# Generated by Django 6.0.4 on 2026-05-09 20:24

from django.db import migrations, models


# Heuristic: classify existing DimensionTypes by their code/name so the
# hub renders Thomas's grouping immediately after migration without an
# admin scrubbing every row by hand.
OPERATIONAL_HINTS = (
    "DEPT", "PROJ", "COST", "STRAT", "STRATEGY", "TEAM", "EMPL",
    "EMPLOYEE",
)
REPORTING_HINTS = ("REGION", "CHANNEL", "SEGMENT", "MATURITY", "ASSETCLASS")
FINANCIAL_HINTS = ("SUBACC", "SUBACCOUNT", "SUB_ACCOUNT")


def backfill_category(apps, schema_editor):
    DimensionType = apps.get_model("beakon_core", "DimensionType")
    for dt in DimensionType.objects.all():
        token = (dt.code or "").upper()
        name = (dt.name or "").upper()
        haystack = f"{token} {name}"
        if any(h in haystack for h in FINANCIAL_HINTS):
            dt.category = "financial"
        elif any(h in haystack for h in OPERATIONAL_HINTS):
            dt.category = "operational"
        elif any(h in haystack for h in REPORTING_HINTS):
            dt.category = "reporting"
        else:
            dt.category = "other"
        dt.save(update_fields=["category"])


def reverse_noop(apps, schema_editor):
    # Nothing to undo — the column drops with the AddField reversal.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0044_openorder_performancesnapshot_portfoliotrade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensiontype',
            name='category',
            field=models.CharField(choices=[('financial', 'Financial'), ('operational', 'Operational'), ('reporting', 'Reporting'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.RunPython(backfill_category, reverse_noop),
    ]
