# Generated by Django 6.0.4 on 2026-05-09 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0046_dimensiontype_category_seed'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('audience', models.CharField(blank=True, help_text='One-line description of the target customer.', max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Null for Enterprise (custom-priced).', max_digits=10, null=True)),
                ('currency', models.CharField(default='CHF', max_length=3)),
                ('billing_cadence', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom (sales-led)')], default='monthly', max_length=10)),
                ('max_entities', models.PositiveIntegerField(default=1, help_text='Soft limit. UI surfaces this; enforcement is per-plan policy.')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of bullet strings shown on the pricing page.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_self_serve', models.BooleanField(default=True, help_text='Self-serve plans accept register-time signups. Sales-led plans (Enterprise) route to /contact.')),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beakon_plan',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Trial expired'), ('cancelled', 'Cancelled')], default='trial', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='When the trial expires. Null after activation.', null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='beakon_core.plan')),
            ],
            options={
                'db_table': 'beakon_org_subscription',
            },
        ),
        migrations.CreateModel(
            name='ActivationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending — awaiting invoice'), ('invoiced', 'Invoice sent'), ('paid', 'Paid — subscription activated'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('invoice_ref', models.CharField(blank=True, max_length=80)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beakon_activation_requests_handled', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beakon_activation_requests', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_requests', to='beakon_core.organizationsubscription')),
            ],
            options={
                'db_table': 'beakon_activation_request',
                'ordering': ['-requested_at'],
            },
        ),
    ]
