# Generated by Django 6.0.4 on 2026-05-12 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0049_seed_location_cc_dimension_types'),
        ('organizations', '0003_backfill_selected_activities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_text', models.TextField(help_text='Plain-language description of what the AI got wrong and how it should behave next time.')),
                ('ai_proposal_snapshot', models.JSONField(blank=True, default=dict, help_text="Snapshot of the AI's proposed JE / extraction at the moment the correction was written. Lets Phase B show 'AI proposed X, you corrected to Y'.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='beakon_core.bill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_corrections_made', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_corrections', to='organizations.organization')),
                ('vendor', models.ForeignKey(help_text='Denormalised from bill.vendor for fast retrieval at extraction time.', on_delete=django.db.models.deletion.PROTECT, related_name='bill_corrections', to='beakon_core.vendor')),
            ],
            options={
                'db_table': 'beakon_billcorrection',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'vendor', '-created_at'], name='beakon_bill_organiz_76b78f_idx'), models.Index(fields=['bill'], name='beakon_bill_bill_id_0f14f4_idx')],
            },
        ),
    ]
