# Generated by Django 6.0.4 on 2026-05-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0050_billcorrection'),
    ]

    operations = [
        migrations.AddField(
            model_name='billcorrection',
            name='error_types',
            field=models.JSONField(blank=True, default=list, help_text='List of structured error-type keys the user checked.'),
        ),
        migrations.AddField(
            model_name='billcorrection',
            name='future_rule_instruction',
            field=models.TextField(blank=True, help_text='Plain-English instruction for future similar invoices. Empty for one-off corrections.'),
        ),
        migrations.AddField(
            model_name='billcorrection',
            name='make_reusable_rule',
            field=models.BooleanField(default=False, help_text='True = user opted to remember this for future invoices.'),
        ),
        migrations.AlterField(
            model_name='billcorrection',
            name='ai_proposal_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text="Snapshot of the AI's proposed JE / extraction at the moment the correction was written. Lets later UIs show 'AI proposed X, you corrected to Y'."),
        ),
        migrations.AlterField(
            model_name='billcorrection',
            name='correction_text',
            field=models.TextField(help_text='Plain-language description of what the AI got wrong on this draft. Always required.'),
        ),
    ]
