# Generated by Django 6.0.4 on 2026-05-12 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0051_billcorrection_error_types_and_more'),
        ('organizations', '0003_backfill_selected_activities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(blank=True, help_text='Vendor-side customer identifier extracted from the originating invoice (e.g. Sunrise 1000779477).', max_length=64)),
                ('invoice_pattern', models.CharField(blank=True, help_text="Free-form description of the invoice pattern this rule applies to (e.g. 'Monthly telecom invoice; Sunrise layout').", max_length=255)),
                ('trigger_conditions', models.JSONField(blank=True, default=dict, help_text='Structured matching conditions evaluated at extraction time. Shape evolves; today the human_instruction is the primary signal.')),
                ('correction_type', models.CharField(blank=True, help_text="Canonical category (duplicate_line, vat_treatment_wrong, wrong_account, etc.) — usually derived from the BillCorrection's error_types.", max_length=64)),
                ('human_instruction', models.TextField(help_text='Plain-English instruction approved by the user. This is what Beakon shows in audit trails and what the AI sees in its prompt when this rule applies.')),
                ('structured_accounting_logic', models.JSONField(blank=True, default=dict, help_text='Machine-readable mapping (target accounts, tax-code overrides, line-merge directives). Populated by later phases as patterns become reliably extractable.')),
                ('scope', models.CharField(choices=[('one_time', 'One-time'), ('vendor', 'Vendor-specific'), ('vendor_customer_number', 'Vendor + customer number'), ('entity', 'Entity-specific'), ('invoice_pattern', 'Invoice pattern')], default='vendor', max_length=32)),
                ('confidence_policy', models.CharField(choices=[('auto_apply', 'Auto-apply'), ('suggest_high_confidence', 'Suggest with high confidence'), ('require_review', 'Require review')], default='require_review', help_text='Defaults to require_review so the first application is supervised — policy graduates with override metrics.', max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0, help_text="Times the reviewer accepted Beakon's output when this rule was in context. ↑ confidence.")),
                ('override_count', models.IntegerField(default=0, help_text="Times the reviewer overrode Beakon's output when this rule was in context. ↓ confidence; persistent overrides should deactivate the rule.")),
                ('is_active', models.BooleanField(default=True, help_text='Inactive rules are skipped at extraction time but kept for audit history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_learning_rules', to=settings.AUTH_USER_MODEL)),
                ('created_from_correction', models.ForeignKey(blank=True, help_text='The specific correction this rule was promoted from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_rules', to='beakon_core.billcorrection')),
                ('created_from_invoice', models.ForeignKey(blank=True, help_text='The bill whose correction produced this rule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_rules_created', to='beakon_core.bill')),
                ('entity', models.ForeignKey(blank=True, help_text='Restrict the rule to a single entity. Null = all entities in this org.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_rules', to='beakon_core.entity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_rules', to='organizations.organization')),
                ('vendor', models.ForeignKey(help_text="Rule applies to this vendor's bills.", on_delete=django.db.models.deletion.PROTECT, related_name='learning_rules', to='beakon_core.vendor')),
            ],
            options={
                'db_table': 'beakon_learningrule',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'vendor', 'is_active', '-created_at'], name='beakon_lear_organiz_a79d1b_idx')],
            },
        ),
    ]
