# Generated by Django 6.0.4 on 2026-05-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0052_learningrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='ai_applied_rule_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
