# Generated by Django 6.0.4 on 2026-05-16 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakon_core', '0053_bill_ai_applied_rule_ids'),
        ('organizations', '0003_backfill_selected_activities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JECorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_vendor_name', models.CharField(blank=True, help_text='AI-extracted vendor name, kept as audit context even when no Vendor record matched.', max_length=255)),
                ('correction_text', models.TextField(help_text='Plain-language description of what the AI got wrong on this draft. Always required.')),
                ('error_types', models.JSONField(blank=True, default=list, help_text='List of structured error-type keys the user checked.')),
                ('make_reusable_rule', models.BooleanField(default=False, help_text='True = user opted to remember this for future entries.')),
                ('future_rule_instruction', models.TextField(blank=True, help_text='Plain-English instruction for future similar entries. Empty for one-off corrections.')),
                ('ai_proposal_snapshot', models.JSONField(blank=True, default=dict, help_text="Snapshot of the AI's proposed JE / extraction at the moment the correction was written.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='je_corrections_made', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='beakon_core.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='je_corrections', to='organizations.organization')),
                ('vendor', models.ForeignKey(blank=True, help_text='Optional — vendor matched by the AI extraction, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='je_corrections', to='beakon_core.vendor')),
            ],
            options={
                'db_table': 'beakon_jecorrection',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'vendor', '-created_at'], name='beakon_jeco_organiz_b6a577_idx'), models.Index(fields=['journal_entry'], name='beakon_jeco_journal_de0849_idx')],
            },
        ),
    ]
