/* Workbook → API resource map.
 *
 * Used by the generic data browser at /dashboard/blueprint/data/[resource]
 * and by the workbook implementation evidence page to send each tab to a
 * concrete table view.
 *
 * Each entry says: how to fetch this resource, what to call it, and which
 * columns to show on the list table. */

export interface ColumnSpec {
  key: string;
  label: string;
  /** "code" → monospace · "flag" → Yes/No · "decimal" → tabular align */
  hint?: "code" | "flag" | "decimal" | "date";
}

export interface WorkbookResourceConfig {
  /** URL slug under /dashboard/blueprint/data/<slug>/ */
  slug: string;
  /** Workbook tab label */
  tab: string;
  /** Page title */
  title: string;
  /** API endpoint relative to /api/v1 (no trailing slash) */
  endpoint: string;
  /** Columns to render */
  columns: ColumnSpec[];
}

const C = (key: string, label: string, hint?: ColumnSpec["hint"]): ColumnSpec =>
  ({ key, label, hint });

export const WORKBOOK_RESOURCES: WorkbookResourceConfig[] = [
  {
    slug: "coa-definitions",
    tab: "01 CoA Definition",
    title: "Charts of Accounts (CoA Definitions)",
    endpoint: "/beakon/coa-definitions",
    columns: [
      C("coa_id", "CoA ID", "code"),
      C("name", "Name"),
      C("coa_type", "Type", "code"),
      C("version_no", "Version"),
      C("status", "Status"),
      C("effective_from", "Effective From", "date"),
      C("effective_to", "Effective To", "date"),
      C("base_currency", "Base CCY"),
      C("default_reporting_currency", "Default Rpt CCY"),
      C("additional_reporting_currencies", "Additional Rpt CCY"),
      C("universal_mapping_required", "Univ. Map Req.", "flag"),
      C("dimensions_enabled", "Dimensions", "flag"),
      C("governed_instruments_enabled", "Governed Instr.", "flag"),
      C("description", "Description"),
      C("notes", "Notes"),
    ],
  },
  {
    slug: "accounts",
    tab: "02 CoA Master",
    title: "Chart of Accounts",
    endpoint: "/beakon/accounts",
    columns: [
      C("code", "Account No", "code"),
      C("name", "Account Name"),
      C("short_name", "Short Name"),
      C("source_account_type", "Account_Type", "code"),
      C("level_no", "Level"),
      C("normal_balance", "Normal Balance"),
      C("posting_allowed", "Posting", "flag"),
      C("header_flag", "Header", "flag"),
      C("mandatory_flag", "Mandatory", "flag"),
      C("scope", "Scope", "code"),
      C("economic_nature", "Economic Nature", "code"),
      C("client_view_category", "Client View Cat.", "code"),
      C("subledger_required", "Subledger req.", "flag"),
      C("subledger_type", "Subledger Type", "code"),
      C("required_dimension_type_codes", "Required Dims", "code"),
      C("optional_dimension_type_codes", "Optional Dims", "code"),
      C("dimension_validation_rule", "Validation Rule"),
      C("universal_map_required", "Universal Map", "flag"),
      C("default_universal_coa_code", "Default Universal", "code"),
      C("mapping_method", "Mapping Method"),
      C("valuation_basis", "Valuation Basis"),
      C("fx_revalue_flag", "FX Revalue", "flag"),
      C("tax_relevant_flag", "Tax Relevant", "flag"),
      C("cashflow_category", "Cashflow Cat."),
      C("report_group", "Report Group"),
      C("allow_foreign_currency_posting", "Foreign CCY", "flag"),
      C("monetary_flag", "Monetary", "flag"),
      C("fx_remeasure_flag", "FX Remeasure"),
      C("fx_gain_loss_bucket", "FX G/L Bucket"),
      C("historical_vs_closing_rate_method", "Hist/Close Rate"),
      C("is_active", "Active", "flag"),
    ],
  },
  {
    slug: "coa-mappings",
    tab: "03 CoA Mapping",
    title: "CoA Mappings (source → universal)",
    endpoint: "/beakon/coa-mappings",
    columns: [
      C("mapping_id", "Mapping ID", "code"),
      C("coa_definition_code", "Source CoA", "code"),
      C("source_account_no", "Source account", "code"),
      C("source_account_name", "Source name"),
      C("universal_coa_code", "Universal code", "code"),
      C("universal_coa_name", "Universal name"),
      C("mapping_type", "Type"),
      C("mapping_percent", "%", "decimal"),
      C("condition_rule", "Condition rule"),
      C("required_dimension", "Required dim", "code"),
      C("effective_from", "Effective from", "date"),
      C("effective_to", "Effective to", "date"),
      C("review_status", "Review"),
      C("approved_by", "Approved by"),
      C("notes", "Notes"),
    ],
  },
  {
    slug: "dimension-types",
    tab: "04 Dimensions Reference",
    title: "Dimension Types",
    endpoint: "/beakon/dimension-types",
    columns: [
      C("code", "Code", "code"),
      C("name", "Name"),
      C("description", "Description"),
      C("applies_to", "Applies To", "code"),
      C("mandatory_flag", "Mandatory", "flag"),
      C("multi_select_allowed", "Multi-Select", "flag"),
      C("master_data_owner", "Master Data Owner"),
      C("hierarchy_allowed", "Hierarchy", "flag"),
      C("active_flag", "Active", "flag"),
      C("notes", "Notes"),
    ],
  },
  {
    slug: "dimension-values",
    tab: "05 Dimension Values",
    title: "Dimension Values",
    endpoint: "/beakon/dimension-values",
    columns: [
      C("dimension_type", "Dim Type"),
      C("code", "Code", "code"),
      C("name", "Name"),
      C("parent_value_code", "Parent Code", "code"),
      C("description", "Description"),
      C("active_flag", "Active", "flag"),
      C("effective_from", "Effective From", "date"),
      C("effective_to", "Effective To", "date"),
      C("external_reference", "External Ref"),
      C("notes", "Notes"),
    ],
  },
  {
    slug: "controlled-lists",
    tab: "06 Controlled Lists",
    title: "Controlled Lists (dropdown registry)",
    endpoint: "/beakon/controlled-lists",
    columns: [
      C("list_name", "List Name"),
      C("list_code", "Code", "code"),
      C("list_value", "Value"),
      C("display_order", "Order"),
      C("active_flag", "Active", "flag"),
      C("description", "Description"),
      C("notes", "Notes"),
    ],
  },
  {
    slug: "loans",
    tab: "07 Loan Master",
    title: "Loan Master",
    endpoint: "/beakon/loans",
    columns: [
      C("loan_id", "Loan ID", "code"),
      C("loan_name", "Loan Name"),
      C("loan_type", "Type"),
      C("loan_side", "Side"),
      C("status", "Status"),
      C("borrower_or_lender_code", "Borrower/Lender", "code"),
      C("related_party_flag", "Related Party", "flag"),
      C("facility_reference", "Facility Ref", "code"),
      C("loan_currency", "Currency"),
      C("principal_original", "Principal Orig", "decimal"),
      C("current_principal_outstanding", "Outstanding", "decimal"),
      C("interest_rate_type", "Rate Type"),
      C("fixed_rate", "Fixed Rate", "decimal"),
      C("reference_rate_code", "Ref Rate", "code"),
      C("spread_bps", "Spread bps", "decimal"),
      C("interest_payment_frequency", "Interest Freq"),
      C("day_count_convention", "Day Count"),
      C("start_date", "Start Date", "date"),
      C("maturity_date", "Maturity", "date"),
      C("repayment_type", "Repayment"),
      C("amortization_method", "Amortisation"),
      C("valuation_basis", "Valuation Basis"),
      C("accrual_required_flag", "Accrual Req.", "flag"),
      C("notes", "Notes"),
    ],
  },
  {
    slug: "instruments",
    tab: "08 Instrument Master",
    title: "Instrument Master",
    endpoint: "/beakon/instruments",
    columns: [
      C("instrument_id", "Instrument ID", "code"),
      C("instrument_name", "Name"),
      C("instrument_type", "Type"),
      C("quoted_unquoted_flag", "Quoted/Unquoted"),
      C("asset_class_code", "Asset Class", "code"),
      C("strategy_code", "Strategy", "code"),
      C("portfolio_default", "Default Portfolio", "code"),
      C("custodian_default", "Default Custodian", "code"),
      C("issuer_or_counterparty_code", "Issuer/CP", "code"),
      C("isin_or_ticker", "ISIN / Ticker", "code"),
      C("currency", "Currency"),
      C("jurisdiction_code", "Jurisdiction", "code"),
      C("tax_lot_required", "Tax Lot Req.", "flag"),
      C("income_type", "Income Type"),
      C("income_frequency", "Income Freq"),
      C("valuation_method", "Valuation Method"),
      C("price_source", "Price Source"),
      C("fx_exposure_flag", "FX Exposure", "flag"),
      C("inception_date", "Inception", "date"),
      C("maturity_date", "Maturity", "date"),
      C("status", "Status"),
    ],
  },
  {
    slug: "dimension-validation-rules",
    tab: "09 Dimension Validation Rules",
    title: "Dimension Validation Rules",
    endpoint: "/beakon/dimension-validation-rules",
    columns: [
      C("rule_id", "Rule ID", "code"),
      C("account_no", "Account No", "code"),
      C("account_name", "Account Name"),
      C("rule_type", "Rule Type"),
      C("trigger_event", "Trigger Event"),
      C("required_dimension_type_codes", "Required Dims", "code"),
      C("optional_dimension_type_codes", "Optional Dims", "code"),
      C("conditional_dimension_type_codes", "Conditional Dims", "code"),
      C("condition_expression", "Condition"),
      C("validation_error_message", "Error Message"),
      C("severity", "Severity"),
      C("master_driver", "Master Driver"),
      C("active_flag", "Active", "flag"),
      C("effective_from", "Effective From", "date"),
      C("effective_to", "Effective To", "date"),
      C("notes", "Notes"),
    ],
  },
  {
    slug: "counterparties",
    tab: "10 Counterparty Master",
    title: "Counterparty Master",
    endpoint: "/beakon/counterparties",
    columns: [
      C("counterparty_id", "ID", "code"),
      C("counterparty_name", "Name"),
      C("short_name", "Short Name"),
      C("counterparty_type", "Type"),
      C("counterparty_subtype", "Subtype"),
      C("status", "Status"),
      C("country_code", "Country"),
      C("jurisdiction_code", "Jurisdiction", "code"),
      C("base_currency", "Base CCY"),
      C("default_payment_currency", "Pay CCY"),
      C("payment_terms", "Payment Terms"),
      C("settlement_method", "Settlement"),
      C("risk_rating", "Risk"),
      C("kyc_status", "KYC"),
      C("aml_risk_level", "AML Risk"),
      C("sanctions_check_flag", "Sanctions OK", "flag"),
      C("related_party_flag", "Related Party", "flag"),
      C("intercompany_flag", "Intercompany", "flag"),
      C("ap_eligible_flag", "AP Elig.", "flag"),
      C("ar_eligible_flag", "AR Elig.", "flag"),
      C("active_flag", "Active", "flag"),
    ],
  },
  {
    slug: "related-parties",
    tab: "11 Related Party Master",
    title: "Related Party Master",
    endpoint: "/beakon/related-parties",
    columns: [
      C("related_party_id", "ID", "code"),
      C("related_party_name", "Name"),
      C("short_name", "Short Name"),
      C("related_party_type", "Type"),
      C("related_party_subtype", "Subtype"),
      C("party_form", "Party Form"),
      C("relationship_to_client", "Relationship"),
      C("ownership_percent", "Ownership %", "decimal"),
      C("control_flag", "Control", "flag"),
      C("beneficiary_flag", "Beneficiary", "flag"),
      C("settlor_flag", "Settlor", "flag"),
      C("director_flag", "Director", "flag"),
      C("signer_flag", "Signer", "flag"),
      C("country_code", "Country"),
      C("base_currency", "Base CCY"),
      C("tax_residence_country", "Tax Residence"),
      C("loan_eligible_flag", "Loan Elig.", "flag"),
      C("net_worth_inclusion_flag", "Net Worth Incl.", "flag"),
      C("status", "Status"),
      C("active_flag", "Active", "flag"),
    ],
  },
  {
    slug: "bank-account-masters",
    tab: "12 Bank Account Master",
    title: "Bank Account Master",
    endpoint: "/beakon/bank-account-masters",
    columns: [
      C("bank_account_id", "ID", "code"),
      C("bank_account_name", "Name"),
      C("short_name", "Short Name"),
      C("account_holder_type", "Holder Type"),
      C("account_holder_id_code", "Holder", "code"),
      C("bank_counterparty_id_code", "Bank CP", "code"),
      C("bank_name", "Bank"),
      C("booking_center", "Booking Center"),
      C("iban_or_account_no_masked", "IBAN/Account", "code"),
      C("swift_bic", "SWIFT/BIC", "code"),
      C("account_currency", "Currency"),
      C("country_code", "Country"),
      C("account_type", "Type"),
      C("account_subtype", "Subtype"),
      C("account_purpose", "Purpose"),
      C("status", "Status"),
      C("posting_allowed_flag", "Posting", "flag"),
      C("restricted_flag", "Restricted", "flag"),
      C("interest_bearing_flag", "Int. Bearing", "flag"),
      C("kyc_status", "KYC"),
      C("active_flag", "Active", "flag"),
    ],
  },
  {
    slug: "custodians",
    tab: "13 Custodian Master",
    title: "Custodian Master",
    endpoint: "/beakon/custodians",
    columns: [
      C("custodian_id", "ID", "code"),
      C("custodian_name", "Name"),
      C("short_name", "Short Name"),
      C("custodian_type", "Type"),
      C("custodian_subtype", "Subtype"),
      C("linked_counterparty_id", "Linked CP", "code"),
      C("legal_entity_name", "Legal Entity"),
      C("booking_center", "Booking Center"),
      C("country_code", "Country"),
      C("base_currency", "Base CCY"),
      C("supports_listed_securities_flag", "Listed", "flag"),
      C("supports_private_assets_flag", "Private", "flag"),
      C("supports_funds_flag", "Funds", "flag"),
      C("supports_derivatives_flag", "Derivatives", "flag"),
      C("supports_digital_assets_flag", "Digital", "flag"),
      C("nominee_holding_flag", "Nominee", "flag"),
      C("segregated_account_flag", "Segregated", "flag"),
      C("status", "Status"),
      C("active_flag", "Active", "flag"),
    ],
  },
  {
    slug: "portfolios",
    tab: "14 Portfolio Master",
    title: "Portfolio Master",
    endpoint: "/beakon/portfolios",
    columns: [
      C("portfolio_id", "ID", "code"),
      C("portfolio_name", "Name"),
      C("short_name", "Short Name"),
      C("portfolio_type", "Type"),
      C("portfolio_subtype", "Subtype"),
      C("owner_type", "Owner Type"),
      C("owner_id", "Owner", "code"),
      C("primary_related_party_id", "Primary RP", "code"),
      C("linked_custodian_id", "Custodian", "code"),
      C("base_currency", "Base CCY"),
      C("reporting_currency", "Reporting CCY"),
      C("country_code", "Country"),
      C("strategy_code", "Strategy", "code"),
      C("asset_allocation_profile", "Allocation"),
      C("discretionary_flag", "Discretionary", "flag"),
      C("consolidation_flag", "Consolidation", "flag"),
      C("net_worth_inclusion_flag", "Net Worth", "flag"),
      C("performance_report_flag", "Perf. Report", "flag"),
      C("posting_allowed_flag", "Posting", "flag"),
      C("status", "Status"),
      C("active_flag", "Active", "flag"),
    ],
  },
  {
    slug: "properties",
    tab: "15 Property Master",
    title: "Property Master",
    endpoint: "/beakon/properties",
    columns: [
      C("property_id", "ID", "code"),
      C("property_name", "Name"),
      C("short_name", "Short Name"),
      C("property_type", "Type"),
      C("property_subtype", "Subtype"),
      C("usage_type", "Usage"),
      C("ownership_type", "Ownership"),
      C("owner_type", "Owner Type"),
      C("owner_id_code", "Owner", "code"),
      C("primary_related_party_id_code", "Primary RP", "code"),
      C("linked_portfolio_id_code", "Portfolio", "code"),
      C("city", "City"),
      C("country_code", "Country"),
      C("property_currency", "Currency"),
      C("acquisition_date", "Acquired", "date"),
      C("acquisition_cost", "Acq. Cost", "decimal"),
      C("current_carrying_value", "Carrying Value", "decimal"),
      C("valuation_method", "Valuation"),
      C("mortgage_linked_flag", "Mortgaged", "flag"),
      C("rental_income_flag", "Rental Income", "flag"),
      C("net_worth_inclusion_flag", "Net Worth", "flag"),
      C("status", "Status"),
      C("active_flag", "Active", "flag"),
    ],
  },
  {
    slug: "policies",
    tab: "16 Policy Master",
    title: "Policy Master",
    endpoint: "/beakon/policies",
    columns: [
      C("policy_id", "ID", "code"),
      C("policy_name", "Name"),
      C("short_name", "Short Name"),
      C("policy_type", "Type"),
      C("policy_subtype", "Subtype"),
      C("policy_owner_type", "Owner Type"),
      C("policy_owner_id_code", "Owner", "code"),
      C("primary_related_party_id_code", "Primary RP", "code"),
      C("insured_party_id_code", "Insured Party", "code"),
      C("insurer_counterparty_id_code", "Insurer", "code"),
      C("policy_number_masked", "Policy No.", "code"),
      C("country_code", "Country"),
      C("policy_currency", "Currency"),
      C("inception_date", "Inception", "date"),
      C("expiry_date", "Expiry", "date"),
      C("renewal_date", "Renewal", "date"),
      C("premium_frequency", "Premium Freq."),
      C("coverage_amount", "Coverage", "decimal"),
      C("deductible_amount", "Deductible", "decimal"),
      C("investment_linked_flag", "Investment-Linked", "flag"),
      C("claim_eligible_flag", "Claim Elig.", "flag"),
      C("status", "Status"),
      C("active_flag", "Active", "flag"),
    ],
  },
  {
    slug: "tax-lots",
    tab: "17 Tax Lot Master",
    title: "Tax Lot Master",
    endpoint: "/beakon/tax-lots",
    columns: [
      C("tax_lot_id", "Tax Lot ID", "code"),
      C("instrument_code", "Instrument", "code"),
      C("portfolio_code", "Portfolio", "code"),
      C("custodian_code", "Custodian", "code"),
      C("account_no", "Account No", "code"),
      C("lot_open_date", "Open Date", "date"),
      C("acquisition_trade_date", "Trade Date", "date"),
      C("settlement_date", "Settlement", "date"),
      C("original_quantity", "Orig Qty", "decimal"),
      C("remaining_quantity", "Remaining Qty", "decimal"),
      C("unit_of_measure", "UoM"),
      C("acquisition_price_per_unit", "Acq. Price/Unit", "decimal"),
      C("acquisition_currency", "Acq. CCY"),
      C("acquisition_fx_rate_to_reporting", "FX Rate", "decimal"),
      C("acquisition_cost_transaction_ccy", "Cost (Txn)", "decimal"),
      C("acquisition_cost_reporting_ccy", "Cost (Rpt)", "decimal"),
      C("cost_basis_method", "Cost Basis"),
      C("lot_status", "Status"),
      C("disposal_date", "Disposal", "date"),
      C("disposed_quantity", "Disposed Qty", "decimal"),
      C("realized_gain_loss_reporting_ccy", "Realized G/L", "decimal"),
      C("wash_sale_flag", "Wash Sale", "flag"),
      C("active_flag", "Active", "flag"),
    ],
  },

  // ── Architecture / Notes-tab extensions (built on top of the workbook) ──

  {
    slug: "pensions",
    tab: "Pension master (Notes-tab TODO)",
    title: "Pension Master (LPP, Pillar 3a/3b, foreign pension, employer DC/DB)",
    endpoint: "/beakon/pensions",
    columns: [
      C("pension_id", "Pension ID", "code"),
      C("pension_name", "Name"),
      C("short_name", "Short Name"),
      C("pension_type", "Type"),
      C("pension_subtype", "Subtype"),
      C("contribution_basis", "Contribution Basis"),
      C("vesting_status", "Vesting"),
      C("holder_related_party_id_code", "Holder", "code"),
      C("provider_counterparty_id_code", "Provider", "code"),
      C("employer_counterparty_id_code", "Employer", "code"),
      C("country_code", "Country"),
      C("pension_currency", "Currency"),
      C("enrollment_date", "Enrolled", "date"),
      C("expected_retirement_date", "Retirement", "date"),
      C("contributions_to_date", "Contrib. to Date", "decimal"),
      C("vested_balance", "Vested Balance", "decimal"),
      C("projected_benefit", "Projected Benefit", "decimal"),
      C("tax_privileged_flag", "Tax Privileged", "flag"),
      C("employer_sponsored_flag", "Employer-Sponsored", "flag"),
      C("net_worth_inclusion_flag", "Net Worth Incl.", "flag"),
      C("status", "Status"),
      C("active_flag", "Active", "flag"),
    ],
  },
  {
    slug: "commitments",
    tab: "Commitment master (Master-tabs TODO)",
    title: "Commitment Master (private-market subscriptions, capital calls)",
    endpoint: "/beakon/commitments",
    columns: [
      C("commitment_id", "Commitment ID", "code"),
      C("commitment_name", "Name"),
      C("short_name", "Short Name"),
      C("commitment_type", "Type"),
      C("commitment_subtype", "Subtype"),
      C("holder_related_party_id_code", "LP / Holder", "code"),
      C("general_partner_counterparty_id_code", "GP / Sponsor", "code"),
      C("vehicle_instrument_id_code", "Vehicle / Fund", "code"),
      C("country_code", "Country"),
      C("commitment_currency", "Currency"),
      C("vintage_year", "Vintage"),
      C("inception_date", "Inception", "date"),
      C("final_close_date", "Final Close", "date"),
      C("expected_term_years", "Term (yr)"),
      C("total_commitment_amount", "Commitment", "decimal"),
      C("called_to_date", "Called to Date", "decimal"),
      C("distributions_to_date", "Distributed", "decimal"),
      C("unfunded_balance", "Unfunded", "decimal"),
      C("nav", "NAV", "decimal"),
      C("management_fee_rate", "Mgmt Fee %", "decimal"),
      C("carried_interest_rate", "Carry %", "decimal"),
      C("recallable_distributions_flag", "Recallable", "flag"),
      C("status", "Status"),
      C("active_flag", "Active", "flag"),
    ],
  },
  {
    slug: "tax-codes",
    tab: "Tax Code (VAT engine — build #2)",
    title: "Tax Codes (VAT/tax rate registry)",
    endpoint: "/beakon/tax-codes",
    columns: [
      C("code", "Code", "code"),
      C("name", "Name"),
      C("country_code", "Country"),
      C("tax_type", "Type"),
      C("rate", "Rate %", "decimal"),
      C("output_account_code", "Output VAT acct", "code"),
      C("input_account_code", "Input VAT acct", "code"),
      C("is_reverse_charge", "Reverse Charge", "flag"),
      C("effective_from", "Effective From", "date"),
      C("effective_to", "Effective To", "date"),
      C("active_flag", "Active", "flag"),
      C("notes", "Notes"),
    ],
  },
  {
    slug: "recognition-rules",
    tab: "Recognition Rule (engine — build #4)",
    title: "Recognition Rules (multi-period revenue/expense allocation)",
    endpoint: "/beakon/recognition-rules",
    columns: [
      C("code", "Code", "code"),
      C("name", "Name"),
      C("entity_code", "Entity", "code"),
      C("rule_type", "Rule Type"),
      C("currency", "CCY"),
      C("total_amount", "Total", "decimal"),
      C("recognized_to_date", "Recognised", "decimal"),
      C("remaining_amount", "Remaining", "decimal"),
      C("start_date", "Start", "date"),
      C("end_date", "End", "date"),
      C("period_type", "Period"),
      C("method", "Method"),
      C("deferral_account_code", "Deferral acct", "code"),
      C("recognition_account_code", "Recognition acct", "code"),
      C("status", "Status"),
    ],
  },
];

export function getResourceConfig(slug: string): WorkbookResourceConfig | undefined {
  return WORKBOOK_RESOURCES.find((r) => r.slug === slug);
}
